package `in`.swip.app

import android.content.Context
import android.content.pm.ApplicationInfo
import android.os.Build
import android.os.SystemClock
import java.io.File
import java.text.SimpleDateFormat
import java.util.Locale
import java.util.concurrent.ExecutorService
import java.util.concurrent.Executors

/**
 * `F-187` — **a flight recorder with a name, so there can be more than one.**
 *
 * > *"We'll have a ritual between us where I'll give you: an export of JSONL
 * > for the bubble chat, a black box export for the POS failures, battery
 * > usage export logs."*
 *
 * `F-176` built exactly this for the floating button and hard-coded one
 * filename into it. Two more recorders are now wanted, and the alternative to
 * this file is three copies of the escaping, the trim, the single-thread queue
 * and the debuggable gate — which `CLAUDE.md` already records as how a thing
 * drifts.
 *
 * ## Why `BubbleTrace` was not folded into this
 *
 * It is scheduled for deletion. [`docs/38`](../../../../../../../docs/38-BUBBLE-TRACE.md)
 * §4 is an eleven-step removal list and §8 says it comes out as soon as
 * `F-180` is confirmed in a second export. Refactoring a file that is about to
 * be deleted — risking its eleven-test JUnit suite and the `check_wiring` gate
 * pinned to its `enabled()` — to remove duplication that expires with it is
 * bad economics. The duplication is temporary **because the other file is**,
 * and that is a reason rather than an excuse.
 *
 * ## What is in the files, and what is not
 *
 * The same rule as `BubbleTrace` and for the same reason: **no captures.** No
 * payloads, no merchant names, no VPAs, no amounts, no geohashes, no location,
 * nothing from the ledger.
 *
 * The POS recorder is the one where that rule takes real discipline, because
 * an APDU exchange is *exactly* where a merchant identifier lives. It records
 * tag **names** and value **lengths**, never values — see `TapTrace`. A debug
 * log that quietly carried a merchant ID off the phone would be a privacy hole
 * opened for convenience in the one app whose whole claim is that nothing
 * leaves it.
 */
class Blackbox private constructor(internal val fileName: String) {

    companion object {
        /**
         * `F-187`. Every tap on a card machine: what arrived, how far it got,
         * and where it stopped.
         */
        val tap = Blackbox("tap-trace.log")

        /**
         * `F-188`. Which part of SWIP was awake, and for how long.
         */
        val power = Blackbox("power-trace.log")

        /** 512 KB, roughly 3,500 events, then the oldest half goes. */
        private const val MAX_BYTES = 512L * 1024L

        /**
         * True only on a debuggable build.
         *
         * `FLAG_DEBUGGABLE` rather than `BuildConfig.DEBUG` because AGP 8 does
         * not generate `BuildConfig` unless a project asks for it, and this
         * project's `build.gradle` is regenerated by `flutter create` on every
         * bootstrap — so a constant that exists today might not exist on the
         * next clean checkout, and the failure would be a compile error in a
         * file nobody edited. `ApplicationInfo` is always there.
         *
         * This is the whole reason the recorders cannot reach a Play Store
         * build, and `check_wiring.py` fails if it stops testing the flag.
         */
        fun enabled(context: Context): Boolean =
            (context.applicationInfo.flags and ApplicationInfo.FLAG_DEBUGGABLE) != 0

        /**
         * One JSONL line. **Pure, and unit-tested** — see `BlackboxTest`.
         *
         * Hand-rolled rather than `org.json`, for one reason that matters:
         * escaping is the part that can silently ruin the file. A device name
         * with a quote in it produces a line no JSON reader will parse, and the
         * first anyone knows is an export that cannot be read — after the bug
         * being chased has already been reproduced and lost. A pure function
         * can be tested; a call into `JSONObject` inside a `Context`-bound
         * object cannot, on the JVM.
         */
        internal fun formatLine(
            atMs: Long,
            upMs: Long,
            pid: Int,
            event: String,
            fields: List<Pair<String, Any?>>,
        ): String {
            val b = StringBuilder(128)
            b.append("{\"t\":").append(quote(stamp.format(atMs)))
            b.append(",\"up\":").append(upMs)
            b.append(",\"pid\":").append(pid)
            b.append(",\"e\":").append(quote(event))
            if (fields.isNotEmpty()) {
                b.append(",\"v\":{")
                fields.forEachIndexed { i, (k, v) ->
                    if (i > 0) b.append(',')
                    b.append(quote(k)).append(':').append(value(v))
                }
                b.append('}')
            }
            return b.append("}\n").toString()
        }

        private val stamp =
            SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ", Locale.US)

        private fun value(v: Any?): String = when (v) {
            null -> "null"
            is Boolean -> if (v) "true" else "false"
            is Int, is Long, is Short, is Byte -> v.toString()
            // A non-finite double is not valid JSON, and writing one produces
            // a file that dies on the line before the interesting one.
            is Float -> if (v.isFinite()) v.toString() else quote(v.toString())
            is Double -> if (v.isFinite()) v.toString() else quote(v.toString())
            else -> quote(v.toString())
        }

        private fun quote(s: String): String {
            val b = StringBuilder(s.length + 2).append('"')
            for (c in s) {
                when {
                    c == '"' -> b.append("\\\"")
                    c == '\\' -> b.append("\\\\")
                    c == '\n' -> b.append("\\n")
                    c == '\r' -> b.append("\\r")
                    c == '\t' -> b.append("\\t")
                    c < ' ' -> b.append("\\u%04x".format(c.code))
                    else -> b.append(c)
                }
            }
            return b.append('"').toString()
        }
    }

    /**
     * One thread, not a pool.
     *
     * A pool would reorder lines, and the order of events is the entire value
     * of the file. Not the main thread either: `log` is called from an APDU
     * handler, which runs on a binder thread with a terminal waiting.
     */
    private val writer: ExecutorService by lazy {
        Executors.newSingleThreadExecutor { r -> Thread(r, "swip-$fileName") }
    }

    @Volatile
    private var greeted = false

    fun file(context: Context): File = File(context.filesDir, fileName)

    /**
     * Record one event.
     *
     * [fields] are the small facts that make a line worth reading later. Keep
     * them short and keep them factual; these files are read by a person
     * looking for a sequence.
     */
    fun log(context: Context, event: String, vararg fields: Pair<String, Any?>) {
        if (!enabled(context)) return

        // Captured HERE, not on the writer thread. The queue can hold a line
        // for a few milliseconds and an event's own time is the thing being
        // reconstructed later.
        val at = System.currentTimeMillis()
        val up = SystemClock.elapsedRealtime()
        val pid = android.os.Process.myPid()
        val app = context.applicationContext

        val first = !greeted
        if (first) greeted = true

        runCatching {
            writer.execute {
                runCatching {
                    val out = file(app)
                    if (first) {
                        // A process boundary is itself a finding: a tap that
                        // failed and a new pid on the next line is a crash,
                        // which is a different story from a terminal walking
                        // away.
                        out.appendText(
                            formatLine(
                                at, up, pid, "process.start",
                                listOf(
                                    "sdk" to Build.VERSION.SDK_INT,
                                    "device" to "${Build.MANUFACTURER} ${Build.MODEL}",
                                ),
                            )
                        )
                    }
                    out.appendText(formatLine(at, up, pid, event, fields.toList()))
                    trim(out)
                }
            }
        }
    }

    /** The whole file, for the export screen. Empty string when there is none. */
    fun dump(context: Context): String =
        runCatching { file(context).takeIf { it.exists() }?.readText() }
            .getOrNull()
            .orEmpty()

    fun clear(context: Context) {
        runCatching { writer.execute { runCatching { file(context).delete() } } }
    }

    /**
     * Keep the newest half once the file passes [MAX_BYTES].
     *
     * Cut at a newline, so the first surviving line is a whole one. A half-line
     * at the top of an exported file reads as corruption and would be the first
     * thing anyone wasted time on.
     */
    private fun trim(out: File) {
        if (out.length() <= MAX_BYTES) return
        val text = out.readText()
        val cut = text.indexOf('\n', text.length / 2)
        out.writeText(if (cut < 0) "" else text.substring(cut + 1))
    }
}
