package `in`.swip.app

import android.content.Context
import android.content.pm.ApplicationInfo
import android.os.Build
import android.os.SystemClock
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.concurrent.ExecutorService
import java.util.concurrent.Executors

/**
 * `F-176` — **a flight recorder for the floating bubble. Temporary, and it
 * cannot reach the Play Store.**
 *
 * > *"can we temporarily inject a detailed tracker into the app build… track
 * > the launcher's complete on/off lifecycle and behavior… so that each time I
 * > give you an exported tracker/log file, we can analyze exactly what
 * > happened before, during, and after the launcher disappeared."*
 *
 * ## Why a recorder rather than more reasoning
 *
 * The bubble hides for four different reasons and **every one of them is
 * silent**: the screen went off, a payment is in progress, SWIP itself came
 * forward, or it is snoozed. From the outside all four look identical — the
 * button is gone. Nothing crashes, nothing logs, and by the time the owner
 * notices, the state that caused it has already moved on.
 *
 * `CLAUDE.md` records that this project's recurring mistake is concluding
 * instead of looking. This is the apparatus for looking.
 *
 * ## The safety property, and why it is not "remember to delete it"
 *
 * Every event is gated on [enabled], which is **`FLAG_DEBUGGABLE`** — set by
 * the build system on a debug APK and absent from anything signed for release.
 * So:
 *
 *   * the debug APK CI builds records everything;
 *   * a Play Store build records **nothing**, with the checks compiled around
 *     dead calls, even if somebody forgets this file exists.
 *
 * That is deliberately stronger than a constant to flip. A reminder in a
 * checklist is a thing that gets missed; a property of the artifact is not.
 * The file still gets deleted once the cause is found — see
 * `docs/38-BUBBLE-TRACE.md` for the removal list — but until then it is
 * **impossible to ship this to a user**.
 *
 * ## What it does not record
 *
 * No payloads, no merchant names, no VPAs, no amounts, no location. Nothing
 * from the ledger. This records *when the button appeared and disappeared and
 * why*, and the fields below are the whole vocabulary. The log is exported by
 * the owner, deliberately, from a screen that says what it contains — and a
 * debug log that quietly carried captures would be a privacy hole opened for
 * convenience, in the one app whose entire claim is that nothing leaves the
 * phone.
 *
 * ## Shape
 *
 * One JSON object per line, appended. JSONL rather than a JSON array because
 * an array has to be closed — and a process killed mid-write is exactly the
 * event most worth recording, so the format must survive never being finished.
 */
object BubbleTrace {

    /** `bubble-trace.log`, in app-private storage. Never on shared storage. */
    private const val FILE = "bubble-trace.log"

    /**
     * Cap, in bytes. At roughly 150 bytes a line this is some 3,500 events,
     * which is days of ordinary use and far more than any one disappearance
     * needs. Past it the oldest half is dropped — see [trim].
     */
    private const val MAX_BYTES = 512L * 1024L

    /**
     * Writes happen on **one** background thread.
     *
     * Not the main thread: this is called from a touch handler and from
     * `applyVisibility`, both of which run on the frame. Not a pool either —
     * a pool would reorder lines, and the order of events is the entire value
     * of the file.
     */
    private val writer: ExecutorService by lazy {
        Executors.newSingleThreadExecutor { r -> Thread(r, "swip-trace") }
    }

    private val stamp = SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ", Locale.US)

    @Volatile
    private var greeted = false

    /**
     * True only on a debuggable build.
     *
     * `FLAG_DEBUGGABLE` rather than `BuildConfig.DEBUG` because AGP 8 does not
     * generate `BuildConfig` unless a project asks for it, and this project's
     * `build.gradle` is regenerated by `flutter create` on every bootstrap — so
     * a constant that exists today might not exist on the next clean checkout,
     * and the failure would be a compile error in a file nobody edited.
     * `ApplicationInfo` is always there.
     */
    fun enabled(context: Context): Boolean =
        (context.applicationInfo.flags and ApplicationInfo.FLAG_DEBUGGABLE) != 0

    fun file(context: Context): File = File(context.filesDir, FILE)

    /**
     * Record one event.
     *
     * [fields] are the small facts that make a line worth reading later — the
     * four inputs to a visibility decision, which component reported a
     * foreground change, what a snooze was set from. Keep them short and keep
     * them factual; this file is read by a person looking for a sequence.
     */
    fun log(context: Context, event: String, vararg fields: Pair<String, Any?>) {
        if (!enabled(context)) return

        // Captured HERE, not on the writer thread. The queue can hold a line
        // for a few milliseconds and an event's own time is the thing being
        // reconstructed later.
        val at = System.currentTimeMillis()
        val up = SystemClock.elapsedRealtime()
        val pid = android.os.Process.myPid()
        val app = context.applicationContext

        val first = !greeted
        if (first) greeted = true

        runCatching {
            writer.execute {
                runCatching {
                    val out = file(app)
                    if (first) {
                        // A process boundary is itself a finding: if the
                        // bubble vanished and the next line is a new pid, the
                        // service was killed rather than hidden.
                        out.appendText(
                            formatLine(
                                at, up, pid, "process.start",
                                listOf(
                                    "sdk" to Build.VERSION.SDK_INT,
                                    "device" to "${Build.MANUFACTURER} ${Build.MODEL}",
                                ),
                            )
                        )
                    }
                    out.appendText(formatLine(at, up, pid, event, fields.toList()))
                    trim(out)
                }
            }
        }
    }

    /** The whole file, for the export screen. Empty string when there is none. */
    fun dump(context: Context): String =
        runCatching { file(context).takeIf { it.exists() }?.readText() }
            .getOrNull()
            .orEmpty()

    fun clear(context: Context) {
        runCatching { writer.execute { runCatching { file(context).delete() } } }
    }

    /**
     * Keep the newest half once the file passes [MAX_BYTES].
     *
     * Cut at a newline, so the first surviving line is a whole one. A
     * half-line at the top of an exported file reads as corruption and would
     * be the first thing anyone wasted time on.
     */
    private fun trim(out: File) {
        if (out.length() <= MAX_BYTES) return
        val text = out.readText()
        val cut = text.indexOf('\n', text.length / 2)
        out.writeText(if (cut < 0) "" else text.substring(cut + 1))
    }

    /**
     * One JSONL line. **Pure, and unit-tested** — see `BubbleTraceTest`.
     *
     * Hand-rolled rather than `org.json`, for one reason that matters: escaping
     * is the part that can silently ruin the file. A device name with a quote
     * in it, or a reason string with a backslash, produces a line that no JSON
     * reader will parse — and the first anyone would know is an export that
     * cannot be read, after the bug being chased has already been reproduced
     * and lost. A pure function can be tested; a call into `JSONObject` inside
     * a `Context`-bound object cannot, on the JVM.
     */
    internal fun formatLine(
        atMs: Long,
        upMs: Long,
        pid: Int,
        event: String,
        fields: List<Pair<String, Any?>>,
    ): String {
        val body = StringBuilder()
        body.append('{')
        body.append("\"t\":").append(quote(stamp.format(Date(atMs))))
        // Monotonic, and the one to trust when comparing two lines: the wall
        // clock jumps when the network corrects it, and a backwards jump in
        // the middle of a trace makes the sequence unreadable.
        body.append(",\"up\":").append(upMs)
        body.append(",\"pid\":").append(pid)
        body.append(",\"e\":").append(quote(event))
        if (fields.isNotEmpty()) {
            body.append(",\"v\":{")
            fields.forEachIndexed { i, (k, v) ->
                if (i > 0) body.append(',')
                body.append(quote(k)).append(':').append(value(v))
            }
            body.append('}')
        }
        body.append("}\n")
        return body.toString()
    }

    private fun value(v: Any?): String = when (v) {
        null -> "null"
        is Boolean, is Int, is Long, is Short, is Byte -> v.toString()
        is Float, is Double ->
            if (v.toDouble().isFinite()) v.toString() else quote(v.toString())
        else -> quote(v.toString())
    }

    /**
     * JSON string escaping.
     *
     * The control-character branch is not theoretical: `Build.MODEL` is
     * manufacturer-supplied and has contained stray characters on real
     * devices, and a raw one below 0x20 is illegal inside a JSON string.
     */
    private fun quote(s: String): String {
        val out = StringBuilder(s.length + 2)
        out.append('"')
        for (c in s) {
            when (c) {
                '"' -> out.append("\\\"")
                '\\' -> out.append("\\\\")
                '\n' -> out.append("\\n")
                '\r' -> out.append("\\r")
                '\t' -> out.append("\\t")
                else ->
                    if (c < ' ') out.append("\\u%04x".format(c.code))
                    else out.append(c)
            }
        }
        out.append('"')
        return out.toString()
    }
}
