package `in`.swip.app

import android.animation.ValueAnimator
import android.annotation.SuppressLint
import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.app.Service
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.content.SharedPreferences
import android.content.pm.ServiceInfo
import android.graphics.PixelFormat
import android.os.Build
import android.os.Handler
import android.os.IBinder
import android.os.Looper
import android.provider.Settings
import android.util.TypedValue
import android.view.Gravity
import android.view.MotionEvent
import android.view.View
import android.view.WindowManager
import android.view.animation.DecelerateInterpolator
import android.view.animation.OvershootInterpolator
import android.widget.ImageView
import android.widget.LinearLayout
import android.widget.TextView
import kotlin.math.abs

/**
 * `F-158` — **the floating bubble. It exists now.**
 *
 * > *"the floater launcher icon is not working"*
 *
 * It was not working because **it had never been built**. `F-131` shipped the
 * permission screen — the explain-then-send-to-Settings flow that `docs/32`
 * §6 calls step 1 — and steps 2 to 6 were never started. The switch on that
 * screen wrote a `SharedPreferences` boolean that nothing on earth read. The
 * permission was granted, the toggle went on, and no bubble appeared, because
 * there was no code anywhere in the project that drew one.
 *
 * This is step 2, and it is the one that makes the feature real: a foreground
 * service holding a `TYPE_APPLICATION_OVERLAY` window, draggable, edge-snapping,
 * suppressing itself where it must, and opening SWIP's scanner on a tap.
 *
 * ## Why the camera is not inside the bubble yet
 *
 * `docs/32` §3 argues the scan window should be CameraX + ML Kit drawn in a
 * second overlay, so the whole interaction happens without leaving the app
 * you are in. That is still right and it is still the goal.
 *
 * It is not in this commit for a concrete, checkable reason rather than a
 * vague one: **CameraX and ML Kit are Gradle dependencies, and this project's
 * `build.gradle` is generated by `flutter create` inside `tool/bootstrap.sh`
 * on every machine and in CI.** Nothing in `android/app/build.gradle` survives
 * a bootstrap, so adding a dependency there would work locally and vanish on
 * the next clean checkout. Making that possible means teaching bootstrap to
 * inject dependencies into a file it generates, which is its own change with
 * its own failure modes, and it should not ride along inside the commit that
 * first makes the bubble appear.
 *
 * So: this bubble opens SWIP's existing, tested scanner — the one that already
 * handles `noDuplicates`, the aim detector, the resolver and the ledger. One
 * app switch instead of zero. That is worse than the goal and enormously
 * better than a toggle that does nothing.
 *
 * ## The rule from `docs/32` §2, actually enforced
 *
 * > **The SWIP bubble never appears over a payment.**
 *
 * Detecting the foreground app normally needs usage-access or an
 * accessibility service, and SWIP asks for neither — so the rule is kept the
 * other way round, using only signals this service already owns:
 *
 * * hidden while the screen is off or the keyguard is up;
 * * hidden for 90 seconds after SWIP hands off a `upi://` intent, because that
 *   is exactly when a payment app is in front of the user;
 * * hidden while SWIP itself is in the foreground, because a bubble over the
 *   app's own scanner is just a smudge on the viewfinder.
 *
 * Every one of those errs towards the bubble being **absent**. An absent
 * bubble costs one extra tap. A bubble over a PIN pad costs the app.
 */
class SwipBubbleService : Service() {

    companion object {
        private const val CHANNEL_ID = "swip.bubble"
        private const val NOTIFICATION_ID = 0x5117

        /** Start it. Idempotent — a second start just re-shows the bubble. */
        const val ACTION_START = "in.swip.app.BUBBLE_START"
        const val ACTION_STOP = "in.swip.app.BUBBLE_STOP"

        /**
         * "Something changed, look again." Carries no information itself —
         * everything it might have carried is in the shared state below,
         * which is the whole point.
         */
        const val ACTION_RE_EVALUATE = "in.swip.app.BUBBLE_LOOK_AGAIN"

        /** `docs/32` §2. Long enough to cover a checkout, short enough to come back. */
        private const val PAYMENT_QUIET_MS = 90_000L

        /** Whether the service is up. Read over the method channel. */
        @Volatile
        var running: Boolean = false
            private set

        // ── one source of truth for "should the bubble be there" ─────────
        //
        // `F-131` kept this in Flutter's `SharedPreferences` under
        // `swip.bubble.enabled`, and that was half the reason the feature
        // looked broken: Dart owned a boolean, Android owned the actual
        // window, and nothing reconciled them. The notification's "Turn off"
        // action makes that split unworkable - it stops the service from a
        // process Dart may not even be running in, and the Settings toggle
        // would still have shown "on" the next time the app opened.
        //
        // So the service owns it, in its own file, and Dart ASKS. There is
        // exactly one place the answer lives and it is the same place the
        // window lives.

        private const val PREFS = "swip.bubble"
        private const val KEY_WANTED = "wanted"

        /**
         * `F-167` — when the bubble is asleep until.
         *
         * Wispr Flow lets you flick the bubble away for the day, and `docs/32`
         * once promised the same. `F-159` **deleted that promise** rather than
         * leave it unkept. This is it, kept.
         *
         * Stored rather than held in memory, because the two things that most
         * want to end a snooze early — the process dying, or the phone
         * restarting — are exactly the two that a field in memory would not
         * survive. A snooze that quietly ends when Android reclaims the
         * process is not a snooze.
         */
        private const val KEY_SNOOZE_UNTIL = "snoozeUntil"

        /** An hour, from the notification. */
        const val ACTION_SNOOZE_HOUR = "in.swip.app.BUBBLE_SNOOZE_HOUR"

        private const val ONE_HOUR_MS = 60L * 60L * 1000L

        /**
         * `SYSTEM_ALERT_WINDOW` became a special, user-granted permission in
         * API 23. Below that it is an ordinary install-time grant, so it is
         * already held and `canDrawOverlays` does not exist to ask.
         * `MainActivity`'s `canDrawOverlays` handler answers the same way, and
         * the two must not disagree - a Settings screen showing "allowed"
         * while the service refuses to start is the shape of bug this whole
         * round is about.
         */
        private fun canOverlay(context: Context): Boolean =
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                Settings.canDrawOverlays(context)
            } else {
                true
            }

        private fun prefs(context: Context): SharedPreferences =
            context.applicationContext
                .getSharedPreferences(PREFS, Context.MODE_PRIVATE)

        /** What the user last asked for, regardless of what is on screen. */
        fun isWanted(context: Context): Boolean =
            prefs(context).getBoolean(KEY_WANTED, false)

        /** Epoch millis the snooze ends at, or 0. Past values read as awake. */
        fun snoozedUntil(context: Context): Long {
            val until = prefs(context).getLong(KEY_SNOOZE_UNTIL, 0L)
            return if (until > System.currentTimeMillis()) until else 0L
        }

        /**
         * Put the bubble to sleep until [until] (epoch millis).
         *
         * Deliberately does **not** clear `KEY_WANTED`. Snoozing and switching
         * off are different intentions: one says "not right now", the other
         * says "not at all", and collapsing them would mean a flick to get the
         * button out of the way silently undid the setup that put it there.
         */
        fun snooze(context: Context, until: Long) {
            prefs(context).edit().putLong(KEY_SNOOZE_UNTIL, until).apply()
            nudge(context)
        }

        /** Snooze until the next local midnight — "the rest of the day". */
        fun snoozeForTheDay(context: Context) {
            val midnight = java.util.Calendar.getInstance().apply {
                add(java.util.Calendar.DAY_OF_YEAR, 1)
                set(java.util.Calendar.HOUR_OF_DAY, 0)
                set(java.util.Calendar.MINUTE, 0)
                set(java.util.Calendar.SECOND, 0)
                set(java.util.Calendar.MILLISECOND, 0)
            }.timeInMillis
            snooze(context, midnight)
        }

        /** Bring it back now. */
        fun wake(context: Context) {
            prefs(context).edit().remove(KEY_SNOOZE_UNTIL).apply()
            nudge(context)
        }

        /**
         * Turn the bubble on. Returns false - and changes nothing - if the
         * overlay permission is not granted, because recording a wish that
         * cannot be honoured is how the old toggle lied.
         */
        fun start(context: Context): Boolean {
            if (!canOverlay(context)) return false
            prefs(context).edit().putBoolean(KEY_WANTED, true).apply()
            val intent = Intent(context, SwipBubbleService::class.java)
                .setAction(ACTION_START)
            // A foreground service cannot be started from the background on
            // Android 12+, so every caller of this is a foregrounded
            // Activity. `runCatching` is the belt for the case where it is
            // not: a ForegroundServiceStartNotAllowedException must not take
            // the app down over a convenience feature.
            return runCatching {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                    context.startForegroundService(intent)
                } else {
                    context.startService(intent)
                }
            }.isSuccess
        }

        /** Turn it off, and remember that. */
        fun stop(context: Context) {
            prefs(context).edit().putBoolean(KEY_WANTED, false).apply()
            runCatching {
                context.stopService(Intent(context, SwipBubbleService::class.java))
            }
        }

        /**
         * Bring the bubble back if the user had it on.
         *
         * Called from [MainActivity.onCreate]. **This is deliberately not a
         * `BOOT_COMPLETED` receiver:** that needs another permission, and a
         * category reader restarting itself the moment a phone boots is a
         * worse trade than the bubble being absent until SWIP is next opened.
         * The cost is one app launch after a reboot, and it is written on the
         * Settings screen rather than left as a surprise.
         */
        fun restoreIfWanted(context: Context) {
            if (!running && isWanted(context)) start(context)
        }

        // ── why the next two are shared state and not events ─────────────
        //
        // **This is the bug that made the bubble look dead after it was
        // built.** Foreground state used to travel only as a broadcast, and
        // `signal` dropped it when the service was not yet `running`. Starting
        // a service is asynchronous: `startForegroundService` returns long
        // before `onStartCommand` runs. So the ordinary first-use sequence —
        //
        //   1. flip the switch, which starts the service
        //   2. press Home, which fires ACTION_APP_BACKGROUND
        //   3. the service reaches `onStartCommand` some time after that
        //
        // lost step 2 entirely. The service came up believing SWIP was still
        // in front, and **the bubble stayed hidden until the user happened to
        // open SWIP and leave it again.** Which reads exactly like a floating
        // button that does not work.
        //
        // An event you can miss is the wrong shape for a fact that is always
        // true or false right now. These are written by `MainActivity` and
        // **read** by `applyVisibility`, so a lost broadcast costs a moment of
        // staleness rather than a permanently wrong answer. The broadcasts
        // still exist, but only to nudge a running service to look again.

        /**
         * Whether SWIP itself is on screen.
         *
         * **Starts `false`, and the default is the interesting part.**
         *
         * The obvious default is `true`: the usual way this service starts is
         * a foregrounded `MainActivity`, since Android 12+ forbids starting a
         * foreground service from the background. But that is not the *only*
         * way. `START_STICKY` restarts it after a process death, and a
         * `BOOT_COMPLETED` receiver starts it after a reboot — and in both of
         * those there is no Activity at all, so nobody would ever correct a
         * `true` and the bubble would hide itself forever.
         *
         * `false` is wrong for at most the few milliseconds between
         * `MainActivity.onResume` and the service starting, and `onResume`
         * claims the foreground **before** it calls `restoreIfWanted`, so even
         * that window is closed.
         */
        @Volatile
        var appInForeground: Boolean = false
            private set

        /** Epoch millis until which the bubble stays out of a payment's way. */
        @Volatile
        var quietUntil: Long = 0L
            private set

        /** Called from `MainActivity.onResume` / `onPause`. */
        fun noteForeground(context: Context, inFront: Boolean) {
            appInForeground = inFront
            nudge(context)
        }

        /**
         * `docs/32` §2 — the bubble never appears over a payment.
         *
         * A timestamp rather than a flag plus a timer, so a signal that
         * arrives before the service exists is still honoured when it starts:
         * the deadline is already in the future and `applyVisibility` reads it.
         */
        fun notePaymentStarted(context: Context) {
            quietUntil = System.currentTimeMillis() + PAYMENT_QUIET_MS
            nudge(context)
        }

        /**
         * Ask a running service to re-read the state above.
         *
         * Safe to lose. `setPackage` keeps it inside SWIP: the receiver is
         * registered `RECEIVER_NOT_EXPORTED`, and an un-packaged broadcast of
         * an action string this specific would still be a needless thing to
         * put on the system bus.
         */
        private fun nudge(context: Context) {
            if (!running) return
            runCatching {
                context.sendBroadcast(
                    Intent(ACTION_RE_EVALUATE).setPackage(context.packageName)
                )
            }
        }
    }

    private lateinit var windows: WindowManager
    private var bubble: View? = null

    /** The pill's text. Held so [peek] never has to guess a child index. */
    private var label: TextView? = null
    private var params: WindowManager.LayoutParams? = null

    private val main = Handler(Looper.getMainLooper())

    /**
     * The one piece of state the service genuinely owns.
     *
     * Screen on/off arrives as a system broadcast that only a live service can
     * receive, and it is seeded from `PowerManager` at start rather than
     * assumed — a service started while the screen is off must not put a
     * bubble on a display nobody is looking at.
     */
    private var screenOff = false

    /**
     * `F-165`. Which side the bubble is parked against.
     *
     * The window is `WRAP_CONTENT` and positioned by its **left** edge, so
     * widening into a pill grows it to the right. Parked on the right-hand
     * side of the screen, that put the label off the edge and "Scanning…"
     * arrived cropped to "S".
     *
     * Knowing the side means the expansion can be compensated for — see
     * [reanchor].
     */
    private var parkedRight = false

    /** Re-show the bubble the moment a payment's quiet window expires. */
    private val unquiet = Runnable { applyVisibility() }

    private val systemEvents = object : BroadcastReceiver() {
        override fun onReceive(context: Context?, intent: Intent?) {
            when (intent?.action) {
                Intent.ACTION_SCREEN_OFF -> screenOff = true
                Intent.ACTION_SCREEN_ON, Intent.ACTION_USER_PRESENT ->
                    screenOff = false
            }
            // Everything else — foreground, payment quiet — is read from the
            // companion rather than carried on the intent, so this handler has
            // nothing to get wrong and a lost broadcast costs nothing.
            applyVisibility()
        }
    }

    override fun onBind(intent: Intent?): IBinder? = null

    override fun onCreate() {
        super.onCreate()
        windows = getSystemService(Context.WINDOW_SERVICE) as WindowManager

        // Seeded, not assumed. A service started while the screen is off (a
        // boot that finishes in a pocket, for instance) must not put a bubble
        // on a display nobody is looking at.
        screenOff = runCatching {
            !(getSystemService(Context.POWER_SERVICE) as android.os.PowerManager)
                .isInteractive
        }.getOrDefault(false)

        startInForeground()

        val filter = IntentFilter().apply {
            addAction(Intent.ACTION_SCREEN_OFF)
            addAction(Intent.ACTION_SCREEN_ON)
            addAction(Intent.ACTION_USER_PRESENT)
            addAction(ACTION_RE_EVALUATE)
        }
        // The three SWIP actions are strictly in-process; the screen ones are
        // system broadcasts. `RECEIVER_NOT_EXPORTED` is correct for both here
        // because protected system broadcasts are delivered regardless.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            registerReceiver(systemEvents, filter, Context.RECEIVER_NOT_EXPORTED)
        } else {
            @Suppress("UnspecifiedRegisterReceiverFlag")
            registerReceiver(systemEvents, filter)
        }
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        if (intent?.action == ACTION_STOP) {
            // The notification's "Turn off". It has to write the preference
            // too, not just stop the service - otherwise `restoreIfWanted`
            // would put the bubble straight back the next time SWIP opened,
            // and the user would have dismissed it for nothing.
            stop(this)
            stopSelf()
            return START_NOT_STICKY
        }

        if (intent?.action == ACTION_SNOOZE_HOUR) {
            // Snooze, not stop: the service stays up so it can come back on
            // its own. Stopping would need something to restart it, and the
            // only thing that does is opening SWIP.
            snooze(this, System.currentTimeMillis() + ONE_HOUR_MS)
            applyVisibility()
            return START_STICKY
        }

        // Without the permission there is nothing to draw and never will be.
        // Stopping rather than sitting there as a dead notification is the
        // honest behaviour.
        if (!canOverlay(this)) {
            stopSelf()
            return START_NOT_STICKY
        }

        if (bubble == null) addBubble()
        running = true
        applyVisibility()
        // START_STICKY: if Android kills the service under memory pressure the
        // user's answer to "should the bubble be there" has not changed, so it
        // should come back.
        return START_STICKY
    }

    override fun onDestroy() {
        running = false
        main.removeCallbacks(unquiet)
        main.removeCallbacks(settle)
        runCatching { unregisterReceiver(systemEvents) }
        removeBubble()
        super.onDestroy()
    }

    // ── the window ──────────────────────────────────────────────────────────

    private fun dp(value: Float): Int = TypedValue.applyDimension(
        TypedValue.COMPLEX_UNIT_DIP, value, resources.displayMetrics
    ).toInt()

    private fun addBubble() {
        val view = buildBubble()

        val lp = WindowManager.LayoutParams(
            WindowManager.LayoutParams.WRAP_CONTENT,
            WindowManager.LayoutParams.WRAP_CONTENT,
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O)
                WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY
            else
                @Suppress("DEPRECATION")
                WindowManager.LayoutParams.TYPE_PHONE,
            // NOT_FOCUSABLE is load-bearing: without it the bubble takes key
            // input from whatever is underneath, so the keyboard closes in the
            // app the user is actually typing in.
            WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE or
                WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,
            PixelFormat.TRANSLUCENT,
        ).apply {
            gravity = Gravity.TOP or Gravity.START
            x = 0
            // Roughly a third down the screen: clear of the status bar, clear
            // of the thumb's resting place, and out of the way of the bottom
            // sheets most apps put their primary action in.
            y = resources.displayMetrics.heightPixels / 3
        }

        runCatching { windows.addView(view, lp) }
            .onSuccess {
                bubble = view
                params = lp
            }
    }

    private fun removeBubble() {
        bubble?.let { v -> runCatching { windows.removeView(v) } }
        bubble = null
        label = null
        params = null
    }

    /**
     * Any reason to be hidden wins, and every reason is **read here** rather
     * than remembered from an event that may never have arrived.
     *
     * That is the whole fix for the bubble that would not appear: this method
     * is called on every start, every system broadcast and every nudge, and
     * each time it asks what is true now.
     */
    private fun applyVisibility() {
        val now = System.currentTimeMillis()
        val quiet = now < quietUntil
        // `F-167`. Read from storage rather than a field, so a snooze survives
        // the process being reclaimed and the phone restarting — which are the
        // two things most likely to happen during one.
        val asleep = snoozedUntil(this)
        val hidden = screenOff || quiet || appInForeground || asleep > 0L
        bubble?.visibility = if (hidden) View.GONE else View.VISIBLE

        // Re-check when whichever timer expires first; nothing else will wake
        // us. A snooze can be hours away, and `postDelayed` holds no wakelock,
        // so this fires late rather than never — acceptable for a button whose
        // whole job at that moment is to be absent.
        main.removeCallbacks(unquiet)
        val next = listOfNotNull(
            if (quiet) quietUntil else null,
            if (asleep > 0L) asleep else null,
        ).minOrNull()
        if (next != null) main.postDelayed(unquiet, next - now + 250L)
    }

    // ── the bubble itself ───────────────────────────────────────────────────

    /**
     * `F-158`. The shape is taken from the assistant overlay in the owner's
     * PDF (pages 22-24): a small circle parked against the screen edge that
     * **expands into a pill** when it has something to say, then settles back.
     *
     * ## Why a horizontal `LinearLayout` and not a `FrameLayout`
     *
     * Because the circle and the pill have to be **the same view at two
     * widths**, and that only works if the width is measured rather than set.
     * The window is `WRAP_CONTENT`; a 32 dp disc between two 8 dp pads
     * measures to exactly the 48 dp minimum, so it is a circle. Show the
     * label and the same measure pass makes it a pill. Nothing computes a
     * width, nothing animates one, and there is no state that can disagree
     * with what is on screen.
     *
     * A `FrameLayout` stacks its children, so the label would have been drawn
     * **on top of** the glyph inside an unchanged circle. That was the first
     * version of this method and it would have shipped as a smudge.
     *
     * The 24 dp corner radius in `swip_bubble_bg.xml` is half of [size]. That
     * is what makes the square case a true circle, and it is why the two
     * numbers have to move together.
     *
     * Built in code rather than inflated from a layout because it is one row
     * with two children, and a layout file for that is a second place to keep
     * in sync for no benefit.
     */
    @SuppressLint("ClickableViewAccessibility")
    private fun buildBubble(): View {
        val size = dp(48f)
        val disc = dp(32f)
        val pad = (size - disc) / 2

        val glyph = ImageView(this).apply {
            // Page 23: the mark is not painted onto the pill, it sits in its
            // own contrasting disc at the leading end. That is what keeps it
            // readable while the pill is widening, and what stops the
            // collapsed circle reading as a glyph lost in empty space.
            setBackgroundResource(R.drawable.swip_bubble_disc)
            setImageResource(R.drawable.swip_bubble_mark)
            // Inset within the disc. `ImageView` fits the drawable into the
            // padded content box, so this is what sizes the slash rather than
            // a second dimension to keep in sync.
            setPadding(dp(6f), dp(6f), dp(6f), dp(6f))
            layoutParams = LinearLayout.LayoutParams(disc, disc)
        }

        val text = TextView(this).apply {
            text = getString(R.string.swip_bubble_peek)
            // The one colour that is safe over SWIP's ink ground, hard-coded
            // for the same reason the drawable's are - see swip_bubble_bg.xml.
            setTextColor(0xFFF2EFE9.toInt())
            textSize = 12f
            maxLines = 1
            // GONE rather than INVISIBLE: INVISIBLE still occupies width, so
            // the bubble would be pill-shaped and empty at rest.
            visibility = View.GONE
            layoutParams = LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.WRAP_CONTENT,
                LinearLayout.LayoutParams.WRAP_CONTENT,
            ).apply {
                marginStart = dp(9f)
                marginEnd = dp(3f)
            }
        }
        label = text

        return LinearLayout(this).apply {
            orientation = LinearLayout.HORIZONTAL
            gravity = Gravity.CENTER_VERTICAL
            // 48 dp is Material's minimum touch target and the floor for this
            // control specifically. The reference bubble measures about 28 dp
            // and is genuinely awkward to hit; SWIP's is pressed one-handed,
            // at a counter, usually in a hurry, so it does not copy that.
            minimumWidth = size
            minimumHeight = size
            setPadding(pad, pad, pad, pad)
            setBackgroundResource(R.drawable.swip_bubble_bg)
            // 84% rather than opaque: present without being a hole punched in
            // whatever the user is reading. `docs/32` §4 - "always there,
            // never in the way".
            alpha = 0.84f
            addView(glyph)
            addView(text)
            // `isClickable` + the `performClick` call in the listener are what
            // make this reachable by TalkBack. A bare `setOnTouchListener` on
            // a non-clickable view is invisible to every accessibility
            // service, which for a floating button is the whole feature gone.
            isClickable = true
            setOnTouchListener(DragAndTap())
            contentDescription = getString(R.string.swip_bubble_description)
        }
    }

    /**
     * Drag, edge-snap, and tap — in one listener, because Android delivers
     * them through the same stream of events and separating them means
     * guessing which one a gesture was going to be before it is finished.
     */
    private inner class DragAndTap : View.OnTouchListener {
        private var downX = 0f
        private var downY = 0f
        private var startX = 0
        private var startY = 0
        private var downAt = 0L
        private var dragging = false

        /**
         * `F-167`. Fires if the finger stays still long enough.
         *
         * Posted on DOWN and cancelled by a drag or a lift, which is how a
         * long-press has to be detected when the same listener also owns
         * dragging: you cannot know a press was long until the moment it
         * becomes one, and by then the gesture may already have been a drag.
         */
        private val longPress = Runnable {
            // `running` as well as `dragging`: the service can be destroyed
            // inside the press timeout, and a snooze nobody asked for is a
            // button that vanishes for a day on its own.
            if (dragging || !running) return@Runnable
            snoozeForTheDay(this@SwipBubbleService)
            // Say so, in the bubble itself, in the moment before it goes. A
            // button that silently disappears when held reads as a bug.
            peek(getString(R.string.swip_bubble_snoozed))
            applyVisibility()
        }

        private val slop by lazy {
            android.view.ViewConfiguration.get(this@SwipBubbleService)
                .scaledTouchSlop
        }

        override fun onTouch(view: View, event: MotionEvent): Boolean {
            val lp = params ?: return false

            when (event.actionMasked) {
                MotionEvent.ACTION_DOWN -> {
                    downX = event.rawX
                    downY = event.rawY
                    startX = lp.x
                    startY = lp.y
                    downAt = System.currentTimeMillis()
                    dragging = false
                    main.postDelayed(
                        longPress,
                        android.view.ViewConfiguration.getLongPressTimeout()
                            .toLong(),
                    )
                    view.animate().scaleX(0.92f).scaleY(0.92f)
                        .setDuration(120).start()
                    return true
                }

                MotionEvent.ACTION_MOVE -> {
                    val dx = event.rawX - downX
                    val dy = event.rawY - downY
                    if (!dragging && (abs(dx) > slop || abs(dy) > slop)) {
                        dragging = true
                        // Moving means this was a drag, not a hold.
                        main.removeCallbacks(longPress)
                    }
                    if (dragging) {
                        lp.x = startX + dx.toInt()
                        lp.y = startY + dy.toInt()
                        runCatching { windows.updateViewLayout(view, lp) }
                    }
                    return true
                }

                MotionEvent.ACTION_UP, MotionEvent.ACTION_CANCEL -> {
                    main.removeCallbacks(longPress)
                    view.animate().scaleX(1f).scaleY(1f)
                        .setDuration(120).start()

                    if (dragging) {
                        snapToEdge(view, lp)
                    } else if (event.actionMasked == MotionEvent.ACTION_UP) {
                        // A tap. `ViewConfiguration`'s long-press timeout is
                        // the right boundary: anything longer was somebody
                        // holding it, probably about to drag, and opening a
                        // scanner under their finger would be a surprise.
                        val held = System.currentTimeMillis() - downAt
                        if (held < android.view.ViewConfiguration
                                .getLongPressTimeout()) {
                            // `performClick` before the work, so an
                            // accessibility service hears the click it is
                            // waiting for. Without it the bubble is a button
                            // TalkBack cannot press.
                            view.performClick()
                            openScanner()
                        }
                    }
                    return true
                }
            }
            return false
        }

        /**
         * Messenger's chat-head behaviour: go to whichever side is nearer,
         * with an overshoot so it reads as landing rather than sliding to a
         * halt.
         */
        private fun snapToEdge(view: View, lp: WindowManager.LayoutParams) {
            val screenWidth = resources.displayMetrics.widthPixels
            val margin = dp(8f)
            parkedRight = lp.x + view.width / 2 >= screenWidth / 2
            val target = if (parkedRight) {
                screenWidth - view.width - margin
            } else {
                margin
            }

            // Keep it on screen vertically too — a bubble dragged off the top
            // is a bubble the user has to reboot to get back.
            val screenHeight = resources.displayMetrics.heightPixels
            // `coerceIn(min, max)` THROWS if max < min, and max here is a
            // computed screen measurement. On a short display - or a foldable
            // read while closed - `screenHeight - height - 72dp` can land
            // under the 8 dp margin, and the exception would be thrown inside
            // a touch handler on a window the user has no way to dismiss.
            // `coerceAtLeast` first makes the range provably non-empty.
            val lowest = (screenHeight - view.height - dp(72f))
                .coerceAtLeast(margin)
            lp.y = lp.y.coerceIn(margin, lowest)

            ValueAnimator.ofInt(lp.x, target).apply {
                duration = 260
                interpolator = OvershootInterpolator(1.1f)
                addUpdateListener {
                    lp.x = it.animatedValue as Int
                    runCatching { windows.updateViewLayout(view, lp) }
                }
                start()
            }
        }
    }

    /**
     * `F-163`. Open the scanner **over** whatever the user is in.
     *
     * This used to launch `MainActivity` with `SwipTile.EXTRA_OPEN_SCANNER`,
     * which opened the whole of SWIP full-screen — so tapping the floating
     * button took you out of the app you were standing in, which is the one
     * thing a floating button exists to avoid.
     *
     * It now opens [SwipHoverActivity]: a transparent Activity in its own
     * task, drawing a card with `ScanPage` in it over the app underneath. Same
     * camera, same detection, same resolver, same ledger — because it is the
     * same widget, not a second implementation of one.
     *
     * The Quick Settings tile still opens `MainActivity`, and should: a tile
     * press happens from the shade with nothing behind it to hover over.
     */
    private fun openScanner() {
        // A brief expansion so the tap is acknowledged before the window
        // appears. `docs/32` §4: the delay before the scanner opens is the
        // thing to hide, and a press animation is how you hide it. It matters
        // more here than it did — the hovering window starts its own Flutter
        // engine, so there is about half a second to cover.
        peek()

        val launch = Intent(this, SwipHoverActivity::class.java).apply {
            // NEW_TASK is required to start an Activity from a Service at all.
            // CLEAR_TOP rather than REORDER_TO_FRONT so a second tap restarts
            // the scanner cleanly instead of resurfacing a card whose camera
            // has already been released.
            addFlags(
                Intent.FLAG_ACTIVITY_NEW_TASK or
                    Intent.FLAG_ACTIVITY_CLEAR_TOP
            )
            // Flutter's own extra. `main()` branches on it: without this the
            // engine would come up as the entire app inside a transparent
            // window, which looks like SWIP has been pasted over the screen.
            putExtra(
                SwipHoverActivity.EXTRA_ROUTE,
                SwipHoverActivity.ROUTE_HOVER,
            )
        }

        runCatching { startActivity(launch) }
    }

    /**
     * Expand to a pill for a moment, then settle back to a circle.
     *
     * The label is held in a field rather than fetched with `getChildAt(1)`.
     * An index is a silent dependency on the order two `addView` calls happen
     * in, thirty lines away; a field breaks at compile time instead.
     */
    private fun peek(message: String = getString(R.string.swip_bubble_peek)) {
        val view = bubble ?: return
        val text = label ?: return
        if (text.visibility == View.VISIBLE) return
        text.text = message

        // This alone is what widens the bubble - the window is WRAP_CONTENT,
        // so making the label visible re-measures it into a pill.
        text.visibility = View.VISIBLE
        reanchor()

        view.animate().scaleX(1.06f).scaleY(1.06f)
            .setInterpolator(DecelerateInterpolator())
            .setDuration(140)
            .withEndAction {
                view.animate().scaleX(1f).scaleY(1f).setDuration(140).start()
            }
            .start()

        main.removeCallbacks(settle)
        main.postDelayed(settle, 900)
    }

    /**
     * `F-165`. Keep the pill on screen when it changes width.
     *
     * A `WRAP_CONTENT` overlay is positioned by its left edge, so showing or
     * hiding the label moves its *right* edge. Parked against the right-hand
     * side that pushed the text off the screen — the owner saw "Scanning…"
     * cropped to a single letter.
     *
     * The new width is not known until the view has been measured, which is
     * why this runs in [View.post] rather than immediately: reading
     * `view.width` on the same frame as the visibility change returns the
     * *old* width, and compensating by that is the same bug with extra steps.
     */
    private fun reanchor() {
        val view = bubble ?: return
        val lp = params ?: return
        view.post {
            if (bubble !== view) return@post
            val margin = dp(8f)
            val screenWidth = resources.displayMetrics.widthPixels
            lp.x = if (parkedRight) screenWidth - view.width - margin else margin
            runCatching { windows.updateViewLayout(view, lp) }
        }
    }

    /**
     * Named rather than a lambda so [peek] can cancel a pending one. Two taps
     * inside 900 ms would otherwise queue two settles, and the second would
     * close the pill the first tap had just reopened.
     */
    private val settle = Runnable {
        label?.visibility = View.GONE
        // Narrowing moves the right edge too, so the circle would otherwise
        // be left sitting where the pill's left edge had been.
        reanchor()
    }

    // ── the notification Android requires ───────────────────────────────────

    /**
     * A foreground service is the price of an overlay that survives the user
     * leaving SWIP, and the notification is the honest part of that price:
     * there is no way to draw over other apps *quietly*, and there should not
     * be.
     *
     * `IMPORTANCE_MIN` so it never makes a sound, never peeks, and sits at the
     * bottom of the shade.
     */
    private fun startInForeground() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val manager = getSystemService(NotificationManager::class.java)
            manager.createNotificationChannel(
                NotificationChannel(
                    CHANNEL_ID,
                    getString(R.string.swip_bubble_channel),
                    NotificationManager.IMPORTANCE_MIN,
                ).apply {
                    description = getString(R.string.swip_bubble_channel_note)
                    setShowBadge(false)
                }
            )
        }

        val open = PendingIntent.getActivity(
            this,
            0,
            Intent(this, MainActivity::class.java)
                .addFlags(Intent.FLAG_ACTIVITY_NEW_TASK),
            PendingIntent.FLAG_IMMUTABLE,
        )

        val stop = PendingIntent.getService(
            this,
            1,
            Intent(this, SwipBubbleService::class.java)
                .setAction(ACTION_STOP),
            PendingIntent.FLAG_IMMUTABLE,
        )

        // `F-167`. The discoverable half of snooze. Long-pressing the bubble
        // is faster, but nobody discovers a long-press; a labelled button in
        // the shade is how people find out the gesture exists at all.
        val snooze = PendingIntent.getService(
            this,
            2,
            Intent(this, SwipBubbleService::class.java)
                .setAction(ACTION_SNOOZE_HOUR),
            PendingIntent.FLAG_IMMUTABLE,
        )

        @Suppress("DEPRECATION")
        val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            Notification.Builder(this, CHANNEL_ID)
        } else {
            // The channel overload is API 26. Below it there are no channels
            // at all, and the one-argument constructor is the only form.
            Notification.Builder(this)
        }

        val notification: Notification =
            builder
                .setSmallIcon(R.drawable.swip_bubble_mark)
                .setContentTitle(getString(R.string.swip_bubble_running))
                .setContentText(getString(R.string.swip_bubble_running_note))
                .setContentIntent(open)
                .addAction(
                    Notification.Action.Builder(
                        null as android.graphics.drawable.Icon?,
                        getString(R.string.swip_bubble_snooze_hour),
                        snooze,
                    ).build()
                )
                .addAction(
                    Notification.Action.Builder(
                        // Explicitly the `Icon?` overload. `Action.Builder`
                        // also has a deprecated `(int, ...)` form, and a bare
                        // `null` resolving to the right one is an accident
                        // waiting for a toolchain bump.
                        null as android.graphics.drawable.Icon?,
                        getString(R.string.swip_bubble_turn_off),
                        stop,
                    ).build()
                )
                .setOngoing(true)
                .build()

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
            // Android 14 demands a type. SPECIAL_USE is the correct one — the
            // bubble is not a media player, a location tracker or a sync. The
            // manifest carries the matching declaration and the justification
            // string a reviewer will read.
            startForeground(
                NOTIFICATION_ID,
                notification,
                ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE,
            )
        } else {
            startForeground(NOTIFICATION_ID, notification)
        }
    }
}
