package `in`.swip.app

import android.animation.ValueAnimator
import android.annotation.SuppressLint
import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.app.Service
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.content.SharedPreferences
import android.content.pm.ServiceInfo
import android.graphics.PixelFormat
import android.os.Build
import android.os.Handler
import android.os.IBinder
import android.os.Looper
import android.provider.Settings
import android.util.TypedValue
import android.view.Gravity
import android.view.MotionEvent
import android.view.View
import android.view.WindowManager
import android.view.animation.DecelerateInterpolator
import android.view.animation.OvershootInterpolator
import android.widget.ImageView
import android.widget.LinearLayout
import android.widget.TextView
import kotlin.math.abs

/**
 * `F-158` — **the floating bubble. It exists now.**
 *
 * > *"the floater launcher icon is not working"*
 *
 * It was not working because **it had never been built**. `F-131` shipped the
 * permission screen — the explain-then-send-to-Settings flow that `docs/32`
 * §6 calls step 1 — and steps 2 to 6 were never started. The switch on that
 * screen wrote a `SharedPreferences` boolean that nothing on earth read. The
 * permission was granted, the toggle went on, and no bubble appeared, because
 * there was no code anywhere in the project that drew one.
 *
 * This is step 2, and it is the one that makes the feature real: a foreground
 * service holding a `TYPE_APPLICATION_OVERLAY` window, draggable, edge-snapping,
 * suppressing itself where it must, and opening SWIP's scanner on a tap.
 *
 * ## Why the camera is not inside the bubble yet
 *
 * `docs/32` §3 argues the scan window should be CameraX + ML Kit drawn in a
 * second overlay, so the whole interaction happens without leaving the app
 * you are in. That is still right and it is still the goal.
 *
 * It is not in this commit for a concrete, checkable reason rather than a
 * vague one: **CameraX and ML Kit are Gradle dependencies, and this project's
 * `build.gradle` is generated by `flutter create` inside `tool/bootstrap.sh`
 * on every machine and in CI.** Nothing in `android/app/build.gradle` survives
 * a bootstrap, so adding a dependency there would work locally and vanish on
 * the next clean checkout. Making that possible means teaching bootstrap to
 * inject dependencies into a file it generates, which is its own change with
 * its own failure modes, and it should not ride along inside the commit that
 * first makes the bubble appear.
 *
 * So: this bubble opens SWIP's existing, tested scanner — the one that already
 * handles `noDuplicates`, the aim detector, the resolver and the ledger. One
 * app switch instead of zero. That is worse than the goal and enormously
 * better than a toggle that does nothing.
 *
 * ## The rule from `docs/32` §2, actually enforced
 *
 * > **The SWIP bubble never appears over a payment.**
 *
 * Detecting the foreground app normally needs usage-access or an
 * accessibility service, and SWIP asks for neither — so the rule is kept the
 * other way round, using only signals this service already owns:
 *
 * * hidden while the screen is off or the keyguard is up;
 * * hidden for 90 seconds after SWIP hands off a `upi://` intent, because that
 *   is exactly when a payment app is in front of the user;
 * * hidden while SWIP itself is in the foreground, because a bubble over the
 *   app's own scanner is just a smudge on the viewfinder.
 *
 * Every one of those errs towards the bubble being **absent**. An absent
 * bubble costs one extra tap. A bubble over a PIN pad costs the app.
 */
class SwipBubbleService : Service() {

    companion object {
        private const val CHANNEL_ID = "swip.bubble"
        private const val NOTIFICATION_ID = 0x5117

        /** Start it. Idempotent — a second start just re-shows the bubble. */
        const val ACTION_START = "in.swip.app.BUBBLE_START"
        const val ACTION_STOP = "in.swip.app.BUBBLE_STOP"

        /**
         * Hide for [PAYMENT_QUIET_MS]. Sent by [MainActivity] the moment it
         * forwards a `upi://` intent to a payment app.
         */
        const val ACTION_PAYMENT_STARTED = "in.swip.app.BUBBLE_QUIET"

        /** SWIP came to the front / went to the back. */
        const val ACTION_APP_FOREGROUND = "in.swip.app.BUBBLE_APP_FG"
        const val ACTION_APP_BACKGROUND = "in.swip.app.BUBBLE_APP_BG"

        /** `docs/32` §2. Long enough to cover a checkout, short enough to come back. */
        private const val PAYMENT_QUIET_MS = 90_000L

        /** Whether the service is up. Read over the method channel. */
        @Volatile
        var running: Boolean = false
            private set

        // ── one source of truth for "should the bubble be there" ─────────
        //
        // `F-131` kept this in Flutter's `SharedPreferences` under
        // `swip.bubble.enabled`, and that was half the reason the feature
        // looked broken: Dart owned a boolean, Android owned the actual
        // window, and nothing reconciled them. The notification's "Turn off"
        // action makes that split unworkable - it stops the service from a
        // process Dart may not even be running in, and the Settings toggle
        // would still have shown "on" the next time the app opened.
        //
        // So the service owns it, in its own file, and Dart ASKS. There is
        // exactly one place the answer lives and it is the same place the
        // window lives.

        private const val PREFS = "swip.bubble"
        private const val KEY_WANTED = "wanted"

        /**
         * `SYSTEM_ALERT_WINDOW` became a special, user-granted permission in
         * API 23. Below that it is an ordinary install-time grant, so it is
         * already held and `canDrawOverlays` does not exist to ask.
         * `MainActivity`'s `canDrawOverlays` handler answers the same way, and
         * the two must not disagree - a Settings screen showing "allowed"
         * while the service refuses to start is the shape of bug this whole
         * round is about.
         */
        private fun canOverlay(context: Context): Boolean =
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                Settings.canDrawOverlays(context)
            } else {
                true
            }

        private fun prefs(context: Context): SharedPreferences =
            context.applicationContext
                .getSharedPreferences(PREFS, Context.MODE_PRIVATE)

        /** What the user last asked for, regardless of what is on screen. */
        fun isWanted(context: Context): Boolean =
            prefs(context).getBoolean(KEY_WANTED, false)

        /**
         * Turn the bubble on. Returns false - and changes nothing - if the
         * overlay permission is not granted, because recording a wish that
         * cannot be honoured is how the old toggle lied.
         */
        fun start(context: Context): Boolean {
            if (!canOverlay(context)) return false
            prefs(context).edit().putBoolean(KEY_WANTED, true).apply()
            val intent = Intent(context, SwipBubbleService::class.java)
                .setAction(ACTION_START)
            // A foreground service cannot be started from the background on
            // Android 12+, so every caller of this is a foregrounded
            // Activity. `runCatching` is the belt for the case where it is
            // not: a ForegroundServiceStartNotAllowedException must not take
            // the app down over a convenience feature.
            return runCatching {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                    context.startForegroundService(intent)
                } else {
                    context.startService(intent)
                }
            }.isSuccess
        }

        /** Turn it off, and remember that. */
        fun stop(context: Context) {
            prefs(context).edit().putBoolean(KEY_WANTED, false).apply()
            runCatching {
                context.stopService(Intent(context, SwipBubbleService::class.java))
            }
        }

        /**
         * Bring the bubble back if the user had it on.
         *
         * Called from [MainActivity.onCreate]. **This is deliberately not a
         * `BOOT_COMPLETED` receiver:** that needs another permission, and a
         * category reader restarting itself the moment a phone boots is a
         * worse trade than the bubble being absent until SWIP is next opened.
         * The cost is one app launch after a reboot, and it is written on the
         * Settings screen rather than left as a surprise.
         */
        fun restoreIfWanted(context: Context) {
            if (!running && isWanted(context)) start(context)
        }

        /**
         * Tell a running bubble something happened.
         *
         * `setPackage` keeps it inside SWIP: the receiver is registered
         * `RECEIVER_NOT_EXPORTED`, and an un-packaged broadcast of an action
         * string this specific would still be a needless thing to put on the
         * system bus.
         */
        fun signal(context: Context, action: String) {
            if (!running) return
            runCatching {
                context.sendBroadcast(
                    Intent(action).setPackage(context.packageName)
                )
            }
        }
    }

    private lateinit var windows: WindowManager
    private var bubble: View? = null

    /** The pill's text. Held so [peek] never has to guess a child index. */
    private var label: TextView? = null
    private var params: WindowManager.LayoutParams? = null

    private val main = Handler(Looper.getMainLooper())

    /** Every reason the bubble is currently not on screen. */
    private var screenOff = false
    private var paymentQuiet = false

    /**
     * **Starts `true`, and that is not a typo.**
     *
     * Android 12+ forbids starting a foreground service from the background,
     * so the only thing that can ever start this service is a `MainActivity`
     * that is on screen at that moment. Which means at the instant
     * `onCreate` runs, SWIP *is* the foreground app - and defaulting this to
     * `false` would put a bubble over the very Settings screen the user just
     * used to switch it on.
     *
     * `MainActivity.onPause` clears it, so the bubble appears the moment they
     * leave SWIP. Which is also when it first becomes useful.
     *
     * The alternative - have `onResume` broadcast the truth - loses a race it
     * cannot win: the broadcast is sent before this service's receiver is
     * registered, so it goes nowhere and the bubble sits over the app until
     * the next time the user switches away and back.
     */
    private var appInFront = true

    private val unquiet = Runnable {
        paymentQuiet = false
        applyVisibility()
    }

    private val systemEvents = object : BroadcastReceiver() {
        override fun onReceive(context: Context?, intent: Intent?) {
            when (intent?.action) {
                Intent.ACTION_SCREEN_OFF -> screenOff = true
                Intent.ACTION_SCREEN_ON, Intent.ACTION_USER_PRESENT ->
                    screenOff = false
                ACTION_PAYMENT_STARTED -> {
                    paymentQuiet = true
                    main.removeCallbacks(unquiet)
                    main.postDelayed(unquiet, PAYMENT_QUIET_MS)
                }
                ACTION_APP_FOREGROUND -> appInFront = true
                ACTION_APP_BACKGROUND -> appInFront = false
            }
            applyVisibility()
        }
    }

    override fun onBind(intent: Intent?): IBinder? = null

    override fun onCreate() {
        super.onCreate()
        windows = getSystemService(Context.WINDOW_SERVICE) as WindowManager
        startInForeground()

        val filter = IntentFilter().apply {
            addAction(Intent.ACTION_SCREEN_OFF)
            addAction(Intent.ACTION_SCREEN_ON)
            addAction(Intent.ACTION_USER_PRESENT)
            addAction(ACTION_PAYMENT_STARTED)
            addAction(ACTION_APP_FOREGROUND)
            addAction(ACTION_APP_BACKGROUND)
        }
        // The three SWIP actions are strictly in-process; the screen ones are
        // system broadcasts. `RECEIVER_NOT_EXPORTED` is correct for both here
        // because protected system broadcasts are delivered regardless.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            registerReceiver(systemEvents, filter, Context.RECEIVER_NOT_EXPORTED)
        } else {
            @Suppress("UnspecifiedRegisterReceiverFlag")
            registerReceiver(systemEvents, filter)
        }
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        if (intent?.action == ACTION_STOP) {
            // The notification's "Turn off". It has to write the preference
            // too, not just stop the service - otherwise `restoreIfWanted`
            // would put the bubble straight back the next time SWIP opened,
            // and the user would have dismissed it for nothing.
            stop(this)
            stopSelf()
            return START_NOT_STICKY
        }

        // Without the permission there is nothing to draw and never will be.
        // Stopping rather than sitting there as a dead notification is the
        // honest behaviour.
        if (!canOverlay(this)) {
            stopSelf()
            return START_NOT_STICKY
        }

        if (bubble == null) addBubble()
        running = true
        applyVisibility()
        // START_STICKY: if Android kills the service under memory pressure the
        // user's answer to "should the bubble be there" has not changed, so it
        // should come back.
        return START_STICKY
    }

    override fun onDestroy() {
        running = false
        main.removeCallbacks(unquiet)
        main.removeCallbacks(settle)
        runCatching { unregisterReceiver(systemEvents) }
        removeBubble()
        super.onDestroy()
    }

    // ── the window ──────────────────────────────────────────────────────────

    private fun dp(value: Float): Int = TypedValue.applyDimension(
        TypedValue.COMPLEX_UNIT_DIP, value, resources.displayMetrics
    ).toInt()

    private fun addBubble() {
        val view = buildBubble()

        val lp = WindowManager.LayoutParams(
            WindowManager.LayoutParams.WRAP_CONTENT,
            WindowManager.LayoutParams.WRAP_CONTENT,
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O)
                WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY
            else
                @Suppress("DEPRECATION")
                WindowManager.LayoutParams.TYPE_PHONE,
            // NOT_FOCUSABLE is load-bearing: without it the bubble takes key
            // input from whatever is underneath, so the keyboard closes in the
            // app the user is actually typing in.
            WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE or
                WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,
            PixelFormat.TRANSLUCENT,
        ).apply {
            gravity = Gravity.TOP or Gravity.START
            x = 0
            // Roughly a third down the screen: clear of the status bar, clear
            // of the thumb's resting place, and out of the way of the bottom
            // sheets most apps put their primary action in.
            y = resources.displayMetrics.heightPixels / 3
        }

        runCatching { windows.addView(view, lp) }
            .onSuccess {
                bubble = view
                params = lp
            }
    }

    private fun removeBubble() {
        bubble?.let { v -> runCatching { windows.removeView(v) } }
        bubble = null
        label = null
        params = null
    }

    /** Any reason to be hidden wins. */
    private fun applyVisibility() {
        val hidden = screenOff || paymentQuiet || appInFront
        bubble?.visibility = if (hidden) View.GONE else View.VISIBLE
    }

    // ── the bubble itself ───────────────────────────────────────────────────

    /**
     * `F-158`. The shape is taken from the assistant overlay in the owner's
     * PDF (pages 22-24): a small circle parked against the screen edge that
     * **expands into a pill** when it has something to say, then settles back.
     *
     * ## Why a horizontal `LinearLayout` and not a `FrameLayout`
     *
     * Because the circle and the pill have to be **the same view at two
     * widths**, and that only works if the width is measured rather than set.
     * The window is `WRAP_CONTENT`; a 32 dp disc between two 8 dp pads
     * measures to exactly the 48 dp minimum, so it is a circle. Show the
     * label and the same measure pass makes it a pill. Nothing computes a
     * width, nothing animates one, and there is no state that can disagree
     * with what is on screen.
     *
     * A `FrameLayout` stacks its children, so the label would have been drawn
     * **on top of** the glyph inside an unchanged circle. That was the first
     * version of this method and it would have shipped as a smudge.
     *
     * The 24 dp corner radius in `swip_bubble_bg.xml` is half of [size]. That
     * is what makes the square case a true circle, and it is why the two
     * numbers have to move together.
     *
     * Built in code rather than inflated from a layout because it is one row
     * with two children, and a layout file for that is a second place to keep
     * in sync for no benefit.
     */
    @SuppressLint("ClickableViewAccessibility")
    private fun buildBubble(): View {
        val size = dp(48f)
        val disc = dp(32f)
        val pad = (size - disc) / 2

        val glyph = ImageView(this).apply {
            // Page 23: the mark is not painted onto the pill, it sits in its
            // own contrasting disc at the leading end. That is what keeps it
            // readable while the pill is widening, and what stops the
            // collapsed circle reading as a glyph lost in empty space.
            setBackgroundResource(R.drawable.swip_bubble_disc)
            setImageResource(R.drawable.swip_bubble_mark)
            // Inset within the disc. `ImageView` fits the drawable into the
            // padded content box, so this is what sizes the slash rather than
            // a second dimension to keep in sync.
            setPadding(dp(6f), dp(6f), dp(6f), dp(6f))
            layoutParams = LinearLayout.LayoutParams(disc, disc)
        }

        val text = TextView(this).apply {
            text = getString(R.string.swip_bubble_peek)
            // The one colour that is safe over SWIP's ink ground, hard-coded
            // for the same reason the drawable's are - see swip_bubble_bg.xml.
            setTextColor(0xFFF2EFE9.toInt())
            textSize = 12f
            maxLines = 1
            // GONE rather than INVISIBLE: INVISIBLE still occupies width, so
            // the bubble would be pill-shaped and empty at rest.
            visibility = View.GONE
            layoutParams = LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.WRAP_CONTENT,
                LinearLayout.LayoutParams.WRAP_CONTENT,
            ).apply {
                marginStart = dp(9f)
                marginEnd = dp(3f)
            }
        }
        label = text

        return LinearLayout(this).apply {
            orientation = LinearLayout.HORIZONTAL
            gravity = Gravity.CENTER_VERTICAL
            // 48 dp is Material's minimum touch target and the floor for this
            // control specifically. The reference bubble measures about 28 dp
            // and is genuinely awkward to hit; SWIP's is pressed one-handed,
            // at a counter, usually in a hurry, so it does not copy that.
            minimumWidth = size
            minimumHeight = size
            setPadding(pad, pad, pad, pad)
            setBackgroundResource(R.drawable.swip_bubble_bg)
            // 84% rather than opaque: present without being a hole punched in
            // whatever the user is reading. `docs/32` §4 - "always there,
            // never in the way".
            alpha = 0.84f
            addView(glyph)
            addView(text)
            // `isClickable` + the `performClick` call in the listener are what
            // make this reachable by TalkBack. A bare `setOnTouchListener` on
            // a non-clickable view is invisible to every accessibility
            // service, which for a floating button is the whole feature gone.
            isClickable = true
            setOnTouchListener(DragAndTap())
            contentDescription = getString(R.string.swip_bubble_description)
        }
    }

    /**
     * Drag, edge-snap, and tap — in one listener, because Android delivers
     * them through the same stream of events and separating them means
     * guessing which one a gesture was going to be before it is finished.
     */
    private inner class DragAndTap : View.OnTouchListener {
        private var downX = 0f
        private var downY = 0f
        private var startX = 0
        private var startY = 0
        private var downAt = 0L
        private var dragging = false

        private val slop by lazy {
            android.view.ViewConfiguration.get(this@SwipBubbleService)
                .scaledTouchSlop
        }

        override fun onTouch(view: View, event: MotionEvent): Boolean {
            val lp = params ?: return false

            when (event.actionMasked) {
                MotionEvent.ACTION_DOWN -> {
                    downX = event.rawX
                    downY = event.rawY
                    startX = lp.x
                    startY = lp.y
                    downAt = System.currentTimeMillis()
                    dragging = false
                    view.animate().scaleX(0.92f).scaleY(0.92f)
                        .setDuration(120).start()
                    return true
                }

                MotionEvent.ACTION_MOVE -> {
                    val dx = event.rawX - downX
                    val dy = event.rawY - downY
                    if (!dragging && (abs(dx) > slop || abs(dy) > slop)) {
                        dragging = true
                    }
                    if (dragging) {
                        lp.x = startX + dx.toInt()
                        lp.y = startY + dy.toInt()
                        runCatching { windows.updateViewLayout(view, lp) }
                    }
                    return true
                }

                MotionEvent.ACTION_UP, MotionEvent.ACTION_CANCEL -> {
                    view.animate().scaleX(1f).scaleY(1f)
                        .setDuration(120).start()

                    if (dragging) {
                        snapToEdge(view, lp)
                    } else if (event.actionMasked == MotionEvent.ACTION_UP) {
                        // A tap. `ViewConfiguration`'s long-press timeout is
                        // the right boundary: anything longer was somebody
                        // holding it, probably about to drag, and opening a
                        // scanner under their finger would be a surprise.
                        val held = System.currentTimeMillis() - downAt
                        if (held < android.view.ViewConfiguration
                                .getLongPressTimeout()) {
                            // `performClick` before the work, so an
                            // accessibility service hears the click it is
                            // waiting for. Without it the bubble is a button
                            // TalkBack cannot press.
                            view.performClick()
                            openScanner()
                        }
                    }
                    return true
                }
            }
            return false
        }

        /**
         * Messenger's chat-head behaviour: go to whichever side is nearer,
         * with an overshoot so it reads as landing rather than sliding to a
         * halt.
         */
        private fun snapToEdge(view: View, lp: WindowManager.LayoutParams) {
            val screenWidth = resources.displayMetrics.widthPixels
            val margin = dp(8f)
            val target = if (lp.x + view.width / 2 < screenWidth / 2) {
                margin
            } else {
                screenWidth - view.width - margin
            }

            // Keep it on screen vertically too — a bubble dragged off the top
            // is a bubble the user has to reboot to get back.
            val screenHeight = resources.displayMetrics.heightPixels
            // `coerceIn(min, max)` THROWS if max < min, and max here is a
            // computed screen measurement. On a short display - or a foldable
            // read while closed - `screenHeight - height - 72dp` can land
            // under the 8 dp margin, and the exception would be thrown inside
            // a touch handler on a window the user has no way to dismiss.
            // `coerceAtLeast` first makes the range provably non-empty.
            val lowest = (screenHeight - view.height - dp(72f))
                .coerceAtLeast(margin)
            lp.y = lp.y.coerceIn(margin, lowest)

            ValueAnimator.ofInt(lp.x, target).apply {
                duration = 260
                interpolator = OvershootInterpolator(1.1f)
                addUpdateListener {
                    lp.x = it.animatedValue as Int
                    runCatching { windows.updateViewLayout(view, lp) }
                }
                start()
            }
        }
    }

    /**
     * `F-158`. Hand off to the scanner SWIP already has.
     *
     * Reuses the Quick Settings tile's route exactly — `SwipTile.EXTRA_OPEN_SCANNER`,
     * read once and cleared through `consumeTileLaunch` — so the bubble and
     * the tile cannot drift apart in what they open, and a rotation cannot
     * replay a launch as a second capture.
     */
    private fun openScanner() {
        // A brief expansion so the tap is acknowledged before the app appears.
        // `docs/32` §4: the delay before the scanner opens is the thing to
        // hide, and a press animation is how you hide it.
        peek()

        val launch = Intent(this, MainActivity::class.java).apply {
            addFlags(
                Intent.FLAG_ACTIVITY_NEW_TASK or
                    Intent.FLAG_ACTIVITY_SINGLE_TOP or
                    Intent.FLAG_ACTIVITY_REORDER_TO_FRONT
            )
            putExtra(SwipTile.EXTRA_OPEN_SCANNER, true)
        }
        runCatching { startActivity(launch) }
    }

    /**
     * Expand to a pill for a moment, then settle back to a circle.
     *
     * The label is held in a field rather than fetched with `getChildAt(1)`.
     * An index is a silent dependency on the order two `addView` calls happen
     * in, thirty lines away; a field breaks at compile time instead.
     */
    private fun peek() {
        val view = bubble ?: return
        val text = label ?: return
        if (text.visibility == View.VISIBLE) return

        // This alone is what widens the bubble - the window is WRAP_CONTENT,
        // so making the label visible re-measures it into a pill.
        text.visibility = View.VISIBLE

        view.animate().scaleX(1.06f).scaleY(1.06f)
            .setInterpolator(DecelerateInterpolator())
            .setDuration(140)
            .withEndAction {
                view.animate().scaleX(1f).scaleY(1f).setDuration(140).start()
            }
            .start()

        main.removeCallbacks(settle)
        main.postDelayed(settle, 900)
    }

    /**
     * Named rather than a lambda so [peek] can cancel a pending one. Two taps
     * inside 900 ms would otherwise queue two settles, and the second would
     * close the pill the first tap had just reopened.
     */
    private val settle = Runnable { label?.visibility = View.GONE }

    // ── the notification Android requires ───────────────────────────────────

    /**
     * A foreground service is the price of an overlay that survives the user
     * leaving SWIP, and the notification is the honest part of that price:
     * there is no way to draw over other apps *quietly*, and there should not
     * be.
     *
     * `IMPORTANCE_MIN` so it never makes a sound, never peeks, and sits at the
     * bottom of the shade.
     */
    private fun startInForeground() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val manager = getSystemService(NotificationManager::class.java)
            manager.createNotificationChannel(
                NotificationChannel(
                    CHANNEL_ID,
                    getString(R.string.swip_bubble_channel),
                    NotificationManager.IMPORTANCE_MIN,
                ).apply {
                    description = getString(R.string.swip_bubble_channel_note)
                    setShowBadge(false)
                }
            )
        }

        val open = PendingIntent.getActivity(
            this,
            0,
            Intent(this, MainActivity::class.java)
                .addFlags(Intent.FLAG_ACTIVITY_NEW_TASK),
            PendingIntent.FLAG_IMMUTABLE,
        )

        val stop = PendingIntent.getService(
            this,
            1,
            Intent(this, SwipBubbleService::class.java)
                .setAction(ACTION_STOP),
            PendingIntent.FLAG_IMMUTABLE,
        )

        @Suppress("DEPRECATION")
        val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            Notification.Builder(this, CHANNEL_ID)
        } else {
            // The channel overload is API 26. Below it there are no channels
            // at all, and the one-argument constructor is the only form.
            Notification.Builder(this)
        }

        val notification: Notification =
            builder
                .setSmallIcon(R.drawable.swip_bubble_mark)
                .setContentTitle(getString(R.string.swip_bubble_running))
                .setContentText(getString(R.string.swip_bubble_running_note))
                .setContentIntent(open)
                .addAction(
                    Notification.Action.Builder(
                        // Explicitly the `Icon?` overload. `Action.Builder`
                        // also has a deprecated `(int, ...)` form, and a bare
                        // `null` resolving to the right one is an accident
                        // waiting for a toolchain bump.
                        null as android.graphics.drawable.Icon?,
                        getString(R.string.swip_bubble_turn_off),
                        stop,
                    ).build()
                )
                .setOngoing(true)
                .build()

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
            // Android 14 demands a type. SPECIAL_USE is the correct one — the
            // bubble is not a media player, a location tracker or a sync. The
            // manifest carries the matching declaration and the justification
            // string a reviewer will read.
            startForeground(
                NOTIFICATION_ID,
                notification,
                ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE,
            )
        } else {
            startForeground(NOTIFICATION_ID, notification)
        }
    }
}
