package `in`.swip.app

import android.annotation.SuppressLint
import android.app.Notification
import android.app.NotificationChannel
import android.app.NotificationManager
import android.app.PendingIntent
import android.app.Service
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.content.SharedPreferences
import android.content.pm.ServiceInfo
import android.graphics.PixelFormat
import android.os.Build
import android.os.Handler
import android.os.IBinder
import android.os.Looper
import android.provider.Settings
import android.util.TypedValue
import android.view.Gravity
import android.view.MotionEvent
import android.view.VelocityTracker
import android.view.View
import android.view.WindowManager
import android.widget.ImageView
import android.widget.LinearLayout
import android.widget.TextView
import androidx.dynamicanimation.animation.DynamicAnimation
import androidx.dynamicanimation.animation.FlingAnimation
import androidx.dynamicanimation.animation.FloatPropertyCompat
import androidx.dynamicanimation.animation.SpringAnimation
import androidx.dynamicanimation.animation.SpringForce
import kotlin.math.abs

/**
 * `F-158` — **the floating bubble. It exists now.**
 *
 * > *"the floater launcher icon is not working"*
 *
 * It was not working because **it had never been built**. `F-131` shipped the
 * permission screen — the explain-then-send-to-Settings flow that `docs/32`
 * §6 calls step 1 — and steps 2 to 6 were never started. The switch on that
 * screen wrote a `SharedPreferences` boolean that nothing on earth read. The
 * permission was granted, the toggle went on, and no bubble appeared, because
 * there was no code anywhere in the project that drew one.
 *
 * This is step 2, and it is the one that makes the feature real: a foreground
 * service holding a `TYPE_APPLICATION_OVERLAY` window, draggable, edge-snapping,
 * suppressing itself where it must, and opening SWIP's scanner on a tap.
 *
 * ## Why the camera is not inside the bubble yet
 *
 * `docs/32` §3 argues the scan window should be CameraX + ML Kit drawn in a
 * second overlay, so the whole interaction happens without leaving the app
 * you are in. That is still right and it is still the goal.
 *
 * It is not in this commit for a concrete, checkable reason rather than a
 * vague one: **CameraX and ML Kit are Gradle dependencies, and this project's
 * `build.gradle` is generated by `flutter create` inside `tool/bootstrap.sh`
 * on every machine and in CI.** Nothing in `android/app/build.gradle` survives
 * a bootstrap, so adding a dependency there would work locally and vanish on
 * the next clean checkout. Making that possible means teaching bootstrap to
 * inject dependencies into a file it generates, which is its own change with
 * its own failure modes, and it should not ride along inside the commit that
 * first makes the bubble appear.
 *
 * So: this bubble opens SWIP's existing, tested scanner — the one that already
 * handles `noDuplicates`, the aim detector, the resolver and the ledger. One
 * app switch instead of zero. That is worse than the goal and enormously
 * better than a toggle that does nothing.
 *
 * ## The rule from `docs/32` §2, actually enforced
 *
 * > **The SWIP bubble never appears over a payment.**
 *
 * Detecting the foreground app normally needs usage-access or an
 * accessibility service, and SWIP asks for neither — so the rule is kept the
 * other way round, using only signals this service already owns:
 *
 * * hidden while the screen is off or the keyguard is up;
 * * hidden for 90 seconds after SWIP hands off a `upi://` intent, because that
 *   is exactly when a payment app is in front of the user;
 * * hidden while SWIP itself is in the foreground, because a bubble over the
 *   app's own scanner is just a smudge on the viewfinder.
 *
 * Every one of those errs towards the bubble being **absent**. An absent
 * bubble costs one extra tap. A bubble over a PIN pad costs the app.
 */
class SwipBubbleService : Service() {

    companion object {
        private const val CHANNEL_ID = "swip.bubble"
        private const val NOTIFICATION_ID = 0x5117

        /** Start it. Idempotent — a second start just re-shows the bubble. */
        const val ACTION_START = "in.swip.app.BUBBLE_START"
        const val ACTION_STOP = "in.swip.app.BUBBLE_STOP"

        /**
         * "Something changed, look again." Carries no information itself —
         * everything it might have carried is in the shared state below,
         * which is the whole point.
         */
        const val ACTION_RE_EVALUATE = "in.swip.app.BUBBLE_LOOK_AGAIN"

        /** `docs/32` §2. Long enough to cover a checkout, short enough to come back. */
        private const val PAYMENT_QUIET_MS = 90_000L

        /** Whether the service is up. Read over the method channel. */
        @Volatile
        var running: Boolean = false
            private set

        // ── one source of truth for "should the bubble be there" ─────────
        //
        // `F-131` kept this in Flutter's `SharedPreferences` under
        // `swip.bubble.enabled`, and that was half the reason the feature
        // looked broken: Dart owned a boolean, Android owned the actual
        // window, and nothing reconciled them. The notification's "Turn off"
        // action makes that split unworkable - it stops the service from a
        // process Dart may not even be running in, and the Settings toggle
        // would still have shown "on" the next time the app opened.
        //
        // So the service owns it, in its own file, and Dart ASKS. There is
        // exactly one place the answer lives and it is the same place the
        // window lives.

        private const val PREFS = "swip.bubble"
        private const val KEY_WANTED = "wanted"

        /**
         * `F-167` — when the bubble is asleep until.
         *
         * Wispr Flow lets you flick the bubble away for the day, and `docs/32`
         * once promised the same. `F-159` **deleted that promise** rather than
         * leave it unkept. This is it, kept.
         *
         * Stored rather than held in memory, because the two things that most
         * want to end a snooze early — the process dying, or the phone
         * restarting — are exactly the two that a field in memory would not
         * survive. A snooze that quietly ends when Android reclaims the
         * process is not a snooze.
         */
        private const val KEY_SNOOZE_UNTIL = "snoozeUntil"

        /** An hour, from the notification. */
        const val ACTION_SNOOZE_HOUR = "in.swip.app.BUBBLE_SNOOZE_HOUR"

        private const val ONE_HOUR_MS = 60L * 60L * 1000L

        /**
         * How long the bubble stays on screen after being snoozed, so the
         * message explaining where it went can be read.
         *
         * Longer than [peek]'s own 900 ms settle would be pointless — the pill
         * has collapsed back to a circle by then and there is nothing left to
         * read. Shorter and the sentence is gone before the eye reaches it.
         */
        private const val GOODBYE_MS = 900L

        /**
         * `SYSTEM_ALERT_WINDOW` became a special, user-granted permission in
         * API 23. Below that it is an ordinary install-time grant, so it is
         * already held and `canDrawOverlays` does not exist to ask.
         * `MainActivity`'s `canDrawOverlays` handler answers the same way, and
         * the two must not disagree - a Settings screen showing "allowed"
         * while the service refuses to start is the shape of bug this whole
         * round is about.
         */
        private fun canOverlay(context: Context): Boolean =
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                Settings.canDrawOverlays(context)
            } else {
                true
            }

        private fun prefs(context: Context): SharedPreferences =
            context.applicationContext
                .getSharedPreferences(PREFS, Context.MODE_PRIVATE)

        /** What the user last asked for, regardless of what is on screen. */
        fun isWanted(context: Context): Boolean =
            prefs(context).getBoolean(KEY_WANTED, false)

        /** Epoch millis the snooze ends at, or 0. Past values read as awake. */
        fun snoozedUntil(context: Context): Long {
            val until = prefs(context).getLong(KEY_SNOOZE_UNTIL, 0L)
            return if (until > System.currentTimeMillis()) until else 0L
        }

        /**
         * Put the bubble to sleep until [until] (epoch millis).
         *
         * Deliberately does **not** clear `KEY_WANTED`. Snoozing and switching
         * off are different intentions: one says "not right now", the other
         * says "not at all", and collapsing them would mean a flick to get the
         * button out of the way silently undid the setup that put it there.
         */
        fun snooze(context: Context, until: Long) {
            prefs(context).edit().putLong(KEY_SNOOZE_UNTIL, until).apply()
            nudge(context)
        }

        /** Snooze until the next local midnight — "the rest of the day". */
        fun snoozeForTheDay(context: Context) {
            val midnight = java.util.Calendar.getInstance().apply {
                add(java.util.Calendar.DAY_OF_YEAR, 1)
                set(java.util.Calendar.HOUR_OF_DAY, 0)
                set(java.util.Calendar.MINUTE, 0)
                set(java.util.Calendar.SECOND, 0)
                set(java.util.Calendar.MILLISECOND, 0)
            }.timeInMillis
            snooze(context, midnight)
        }

        /** Bring it back now. */
        fun wake(context: Context) {
            prefs(context).edit().remove(KEY_SNOOZE_UNTIL).apply()
            nudge(context)
        }

        /**
         * Turn the bubble on. Returns false - and changes nothing - if the
         * overlay permission is not granted, because recording a wish that
         * cannot be honoured is how the old toggle lied.
         */
        fun start(context: Context): Boolean {
            if (!canOverlay(context)) return false
            prefs(context).edit().putBoolean(KEY_WANTED, true).apply()
            val intent = Intent(context, SwipBubbleService::class.java)
                .setAction(ACTION_START)
            // A foreground service cannot be started from the background on
            // Android 12+, so every caller of this is a foregrounded
            // Activity. `runCatching` is the belt for the case where it is
            // not: a ForegroundServiceStartNotAllowedException must not take
            // the app down over a convenience feature.
            return runCatching {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                    context.startForegroundService(intent)
                } else {
                    context.startService(intent)
                }
            }.isSuccess
        }

        /** Turn it off, and remember that. */
        fun stop(context: Context) {
            prefs(context).edit().putBoolean(KEY_WANTED, false).apply()
            runCatching {
                context.stopService(Intent(context, SwipBubbleService::class.java))
            }
        }

        /**
         * Bring the bubble back if the user had it on.
         *
         * Called from [MainActivity.onCreate]. **This is deliberately not a
         * `BOOT_COMPLETED` receiver:** that needs another permission, and a
         * category reader restarting itself the moment a phone boots is a
         * worse trade than the bubble being absent until SWIP is next opened.
         * The cost is one app launch after a reboot, and it is written on the
         * Settings screen rather than left as a surprise.
         */
        fun restoreIfWanted(context: Context) {
            if (!running && isWanted(context)) start(context)
        }

        // ── why the next two are shared state and not events ─────────────
        //
        // **This is the bug that made the bubble look dead after it was
        // built.** Foreground state used to travel only as a broadcast, and
        // `signal` dropped it when the service was not yet `running`. Starting
        // a service is asynchronous: `startForegroundService` returns long
        // before `onStartCommand` runs. So the ordinary first-use sequence —
        //
        //   1. flip the switch, which starts the service
        //   2. press Home, which fires ACTION_APP_BACKGROUND
        //   3. the service reaches `onStartCommand` some time after that
        //
        // lost step 2 entirely. The service came up believing SWIP was still
        // in front, and **the bubble stayed hidden until the user happened to
        // open SWIP and leave it again.** Which reads exactly like a floating
        // button that does not work.
        //
        // An event you can miss is the wrong shape for a fact that is always
        // true or false right now. These are written by `MainActivity` and
        // **read** by `applyVisibility`, so a lost broadcast costs a moment of
        // staleness rather than a permanently wrong answer. The broadcasts
        // still exist, but only to nudge a running service to look again.

        /**
         * Whether SWIP itself is on screen.
         *
         * **Starts `false`, and the default is the interesting part.**
         *
         * The obvious default is `true`: the usual way this service starts is
         * a foregrounded `MainActivity`, since Android 12+ forbids starting a
         * foreground service from the background. But that is not the *only*
         * way. `START_STICKY` restarts it after a process death, and a
         * `BOOT_COMPLETED` receiver starts it after a reboot — and in both of
         * those there is no Activity at all, so nobody would ever correct a
         * `true` and the bubble would hide itself forever.
         *
         * `false` is wrong for at most the few milliseconds between
         * `MainActivity.onResume` and the service starting, and `onResume`
         * claims the foreground **before** it calls `restoreIfWanted`, so even
         * that window is closed.
         */
        @Volatile
        var appInForeground: Boolean = false
            private set

        /** Epoch millis until which the bubble stays out of a payment's way. */
        @Volatile
        var quietUntil: Long = 0L
            private set

        /** Called from `MainActivity.onResume` / `onPause`. */
        fun noteForeground(context: Context, inFront: Boolean) {
            appInForeground = inFront
            nudge(context)
        }

        /**
         * `docs/32` §2 — the bubble never appears over a payment.
         *
         * A timestamp rather than a flag plus a timer, so a signal that
         * arrives before the service exists is still honoured when it starts:
         * the deadline is already in the future and `applyVisibility` reads it.
         */
        fun notePaymentStarted(context: Context) {
            quietUntil = System.currentTimeMillis() + PAYMENT_QUIET_MS
            nudge(context)
        }

        /**
         * Ask a running service to re-read the state above.
         *
         * Safe to lose. `setPackage` keeps it inside SWIP: the receiver is
         * registered `RECEIVER_NOT_EXPORTED`, and an un-packaged broadcast of
         * an action string this specific would still be a needless thing to
         * put on the system bus.
         */
        private fun nudge(context: Context) {
            if (!running) return
            runCatching {
                context.sendBroadcast(
                    Intent(ACTION_RE_EVALUATE).setPackage(context.packageName)
                )
            }
        }
    }

    private lateinit var windows: WindowManager
    private var bubble: View? = null

    /** The pill's text. Held so [peek] never has to guess a child index. */
    private var label: TextView? = null
    private var params: WindowManager.LayoutParams? = null

    private val main = Handler(Looper.getMainLooper())

    /**
     * The one piece of state the service genuinely owns.
     *
     * Screen on/off arrives as a system broadcast that only a live service can
     * receive, and it is seeded from `PowerManager` at start rather than
     * assumed — a service started while the screen is off must not put a
     * bubble on a display nobody is looking at.
     */
    private var screenOff = false

    /**
     * What [show] last decided, so a no-op call is a no-op.
     *
     * Starts `false` because the bubble genuinely is not on screen until the
     * first `applyVisibility` — which means the very first appearance pops,
     * which is the one appearance most worth popping.
     */
    private var wasVisible = false

    /**
     * `F-170`. Epoch millis until which [show] refuses to hide the bubble.
     *
     * ## The bug this fixes, which is the `F-169` shape again
     *
     * `F-167` added the long-press snooze and, with it, a line promising the
     * bubble would announce itself before going — *"a button that silently
     * disappears when held reads as a bug"*. The string exists, the [peek]
     * call is there, and **nobody has ever seen it.**
     *
     * The long-press handler peeks the message and then calls
     * `applyVisibility`, which finds a snooze in storage and sets the window
     * `GONE` — on the same frame. The pill was made visible and taken away
     * before one frame had been drawn with it in. Finished, correct,
     * unreachable: the shape `check_wiring.py` exists for, and the shape it
     * cannot see, because every individual piece works.
     *
     * A grace period rather than reordering the two calls, because `snooze()`
     * also `nudge()`s and that broadcast comes back a few milliseconds later
     * to hide the bubble anyway. The only place that can honour "say goodbye
     * first" is the method that does the hiding.
     */
    private var goodbyeUntil = 0L

    /**
     * `F-165`. Which side the bubble is parked against.
     *
     * The window is `WRAP_CONTENT` and positioned by its **left** edge, so
     * widening into a pill grows it to the right. Parked on the right-hand
     * side of the screen, that put the label off the edge and "Scanning…"
     * arrived cropped to "S".
     *
     * Knowing the side means the expansion can be compensated for — see
     * [reanchor].
     */
    private var parkedRight = false

    /** Re-show the bubble the moment a payment's quiet window expires. */
    private val unquiet = Runnable { applyVisibility() }

    // ── the physics ─────────────────────────────────────────────────────────
    //
    // `F-170`. **Everything the bubble does is a spring or a fling now, and
    // none of it has a duration.**
    //
    // > *"make it as beautiful and as seamless as the messenger bubble icon
    // > that comes and pops up … so it feels very native rather than too much
    // > sticky type experience"*
    //
    // That word — sticky — is an accurate description of what a fixed-duration
    // interpolator does. The old edge snap was
    // `ValueAnimator` + `OvershootInterpolator(1.1f)` + `duration = 260`, and
    // a duration is the problem: **a hard flick and a gentle nudge both took
    // 260 ms.** Throw the bubble across the screen and it crawls; push it a
    // centimetre and it lurches. The motion is not related to what the finger
    // did, so it reads as an animation being played *at* you rather than an
    // object you are holding.
    //
    // A `SpringAnimation` has no duration. It has a rest position, a
    // stiffness, a damping ratio and — the part that matters — a **start
    // velocity**, which is handed straight from the `VelocityTracker` that was
    // watching the finger. The same gesture that threw it is the thing that
    // decides how fast it arrives, so a flick lands hard and a nudge drifts.
    //
    // ## Where this came from
    //
    // Asked to go and look at how other people do this. The open-source chat
    // heads all reach for the same idea:
    //
    //   * flipkart-incubator/springy-heads — spring physics per head
    //   * Crdzbird/floaty_chatheads — Facebook Rebound, the library Facebook
    //     wrote for chat heads before Android had its own
    //   * txusballesteros/bubbles-for-android, henrychuangtw/Android-ChatHead
    //
    // Rebound is what Messenger itself used. Android has since absorbed the
    // idea as `androidx.dynamicanimation` — same maths, ~50 KB, first-party,
    // no third-party animation runtime in an app whose selling point is that
    // it does not phone home. That is the dependency `bootstrap.sh` now
    // injects, and it is the first real use of the `F-161` mechanism.
    //
    // ## Why a `FloatPropertyCompat` and not `DynamicAnimation.X`
    //
    // The built-in `DynamicAnimation.X` / `.Y` animate a **View's** position
    // inside its parent. This bubble has no parent — it is its own window, and
    // it moves by mutating `WindowManager.LayoutParams` and calling
    // `updateViewLayout`. So the property is written by hand: the getter reads
    // the layout params, the setter writes them and pushes the window. The
    // spring does not know or care that it is driving a window rather than a
    // view, which is the whole point of the abstraction.

    /**
     * The window's left edge, as something a spring can pull on.
     *
     * `runCatching` because `updateViewLayout` throws if the window has
     * already been removed, and an animation outlives its view by up to a
     * frame — the service can be stopped mid-flight. A crash inside an
     * animation callback would take the whole app down for the sake of a
     * bubble that was on its way out anyway.
     */
    private val windowX = object : FloatPropertyCompat<View>("windowX") {
        override fun getValue(view: View): Float = (params?.x ?: 0).toFloat()
        override fun setValue(view: View, value: Float) {
            val lp = params ?: return
            lp.x = value.toInt()
            runCatching { windows.updateViewLayout(view, lp) }
        }
    }

    private val windowY = object : FloatPropertyCompat<View>("windowY") {
        override fun getValue(view: View): Float = (params?.y ?: 0).toFloat()
        override fun setValue(view: View, value: Float) {
            val lp = params ?: return
            lp.y = value.toInt()
            runCatching { windows.updateViewLayout(view, lp) }
        }
    }

    /**
     * Held as fields, one per property, and **reused** rather than recreated.
     *
     * This is not a micro-optimisation, it is the interruption behaviour. A
     * running `SpringAnimation` handed a new `animateToFinalPosition` keeps
     * its current position *and its current velocity* and re-aims — so
     * grabbing the bubble mid-flight, or a second peek arriving during the
     * first one's settle, is continuous motion. Building a fresh animation
     * each time would start it from a standstill, which is the visible
     * stutter this whole change exists to remove.
     */
    private var slideX: SpringAnimation? = null
    private var settleY: SpringAnimation? = null
    private var glideY: FlingAnimation? = null
    private var popX: SpringAnimation? = null
    private var popY: SpringAnimation? = null

    private fun springFor(
        view: View,
        property: FloatPropertyCompat<View>,
        stiffness: Float,
        damping: Float,
    ): SpringAnimation = SpringAnimation(view, property).apply {
        // `setSpring(...)`, `setStiffness(...)` and `setDampingRatio(...)`
        // spelled out as calls rather than as Kotlin property assignments.
        // Every setter in `dynamicanimation` returns the object for chaining,
        // and **Kotlin only synthesises a property for a setter returning
        // void** — so `spring = …` and `stiffness = …` do not compile here.
        // They look like they should, which is why this note exists.
        setSpring(
            SpringForce().also {
                it.setStiffness(stiffness)
                it.setDampingRatio(damping)
            }
        )
    }

    /** Build every animation this bubble will ever need, once, on add. */
    private fun buildPhysics(view: View) {
        // LOW stiffness + LOW_BOUNCY: it travels a visible distance, so the
        // eye can follow it across, and it settles with one small overshoot
        // rather than the wobble MEDIUM_BOUNCY gives — a bubble that jiggles
        // twice after landing looks like a toy.
        slideX = springFor(
            view, windowX,
            SpringForce.STIFFNESS_LOW,
            SpringForce.DAMPING_RATIO_LOW_BOUNCY,
        )
        // NO_BOUNCY vertically. Horizontal overshoot reads as landing against
        // the edge; vertical overshoot reads as the bubble having been
        // *dropped*, because there is no edge there to land on.
        settleY = springFor(
            view, windowY,
            SpringForce.STIFFNESS_LOW,
            SpringForce.DAMPING_RATIO_NO_BOUNCY,
        )
        // The press, and the pop-in. MEDIUM_BOUNCY is right for scale in a way
        // it is not for position: a button that squashes and springs back with
        // a little life is the single clearest "this is a real control"
        // signal, and it is what makes the Messenger head feel alive.
        popX = springFor(
            view, DynamicAnimation.SCALE_X,
            SpringForce.STIFFNESS_MEDIUM,
            SpringForce.DAMPING_RATIO_MEDIUM_BOUNCY,
        )
        popY = springFor(
            view, DynamicAnimation.SCALE_Y,
            SpringForce.STIFFNESS_MEDIUM,
            SpringForce.DAMPING_RATIO_MEDIUM_BOUNCY,
        )
    }

    /** Stop everything mid-flight. Called on touch-down and on removal. */
    private fun cancelMotion() {
        runCatching { slideX?.cancel() }
        runCatching { settleY?.cancel() }
        runCatching { glideY?.cancel() }
        glideY = null
    }

    /**
     * Spring both scales to [to]. The press, the release and the pop-in.
     *
     * The explicit zero matters because a `DynamicAnimation` **keeps its start
     * velocity after being cancelled** — `endAnimationInternal` clears the
     * start *value* and leaves the velocity alone. So a press arriving after a
     * cancelled [kickScale] would inherit that kick and shoot past its target.
     *
     * It costs nothing when the spring is already running: `SpringAnimation`
     * reads the start velocity only at `start()`, and
     * `animateToFinalPosition` on a running spring just re-aims it, keeping
     * the motion it already has. Zeroing here is therefore "clean start when
     * stopped, continuous when moving", which is what both callers want.
     */
    private fun scaleTo(to: Float) {
        popX?.apply { setStartVelocity(0f); animateToFinalPosition(to) }
        popY?.apply { setStartVelocity(0f); animateToFinalPosition(to) }
    }

    /**
     * Shove the bubble outwards and let it come back by itself.
     *
     * A spring whose rest position is already where it is, handed a velocity,
     * overshoots and settles — which is a bulge with no duration, no end
     * callback and nothing to cancel. See [peek] for why the chained version
     * that used to live there had to go.
     */
    private fun kickScale(velocity: Float) {
        // `cancel()` first, and this is the one place it is right to. A start
        // velocity is only read at `start()`, so kicking a spring that is
        // already running — a peek during the pop-in, say — would be silently
        // ignored and the bubble would not acknowledge the tap at all. Here
        // the bump IS the feedback, so it has to be guaranteed rather than
        // merged.
        for (spring in listOfNotNull(popX, popY)) {
            spring.cancel()
            spring.setStartVelocity(velocity)
            spring.animateToFinalPosition(1f)
        }
    }

    private val systemEvents = object : BroadcastReceiver() {
        override fun onReceive(context: Context?, intent: Intent?) {
            when (intent?.action) {
                Intent.ACTION_SCREEN_OFF -> screenOff = true
                Intent.ACTION_SCREEN_ON, Intent.ACTION_USER_PRESENT ->
                    screenOff = false
            }
            // Everything else — foreground, payment quiet — is read from the
            // companion rather than carried on the intent, so this handler has
            // nothing to get wrong and a lost broadcast costs nothing.
            applyVisibility()
        }
    }

    override fun onBind(intent: Intent?): IBinder? = null

    override fun onCreate() {
        super.onCreate()
        windows = getSystemService(Context.WINDOW_SERVICE) as WindowManager

        // Seeded, not assumed. A service started while the screen is off (a
        // boot that finishes in a pocket, for instance) must not put a bubble
        // on a display nobody is looking at.
        screenOff = runCatching {
            !(getSystemService(Context.POWER_SERVICE) as android.os.PowerManager)
                .isInteractive
        }.getOrDefault(false)

        startInForeground()

        val filter = IntentFilter().apply {
            addAction(Intent.ACTION_SCREEN_OFF)
            addAction(Intent.ACTION_SCREEN_ON)
            addAction(Intent.ACTION_USER_PRESENT)
            addAction(ACTION_RE_EVALUATE)
        }
        // The three SWIP actions are strictly in-process; the screen ones are
        // system broadcasts. `RECEIVER_NOT_EXPORTED` is correct for both here
        // because protected system broadcasts are delivered regardless.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            registerReceiver(systemEvents, filter, Context.RECEIVER_NOT_EXPORTED)
        } else {
            @Suppress("UnspecifiedRegisterReceiverFlag")
            registerReceiver(systemEvents, filter)
        }
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        if (intent?.action == ACTION_STOP) {
            // The notification's "Turn off". It has to write the preference
            // too, not just stop the service - otherwise `restoreIfWanted`
            // would put the bubble straight back the next time SWIP opened,
            // and the user would have dismissed it for nothing.
            stop(this)
            stopSelf()
            return START_NOT_STICKY
        }

        if (intent?.action == ACTION_SNOOZE_HOUR) {
            // Snooze, not stop: the service stays up so it can come back on
            // its own. Stopping would need something to restart it, and the
            // only thing that does is opening SWIP.
            snooze(this, System.currentTimeMillis() + ONE_HOUR_MS)
            applyVisibility()
            return START_STICKY
        }

        // Without the permission there is nothing to draw and never will be.
        // Stopping rather than sitting there as a dead notification is the
        // honest behaviour.
        if (!canOverlay(this)) {
            stopSelf()
            return START_NOT_STICKY
        }

        if (bubble == null) addBubble()
        running = true
        applyVisibility()
        // START_STICKY: if Android kills the service under memory pressure the
        // user's answer to "should the bubble be there" has not changed, so it
        // should come back.
        return START_STICKY
    }

    override fun onDestroy() {
        running = false
        main.removeCallbacks(unquiet)
        main.removeCallbacks(settle)
        runCatching { unregisterReceiver(systemEvents) }
        removeBubble()
        super.onDestroy()
    }

    // ── the window ──────────────────────────────────────────────────────────

    private fun dp(value: Float): Int = TypedValue.applyDimension(
        TypedValue.COMPLEX_UNIT_DIP, value, resources.displayMetrics
    ).toInt()

    private fun addBubble() {
        val view = buildBubble()

        val lp = WindowManager.LayoutParams(
            WindowManager.LayoutParams.WRAP_CONTENT,
            WindowManager.LayoutParams.WRAP_CONTENT,
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O)
                WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY
            else
                @Suppress("DEPRECATION")
                WindowManager.LayoutParams.TYPE_PHONE,
            // NOT_FOCUSABLE is load-bearing: without it the bubble takes key
            // input from whatever is underneath, so the keyboard closes in the
            // app the user is actually typing in.
            WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE or
                WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS,
            PixelFormat.TRANSLUCENT,
        ).apply {
            gravity = Gravity.TOP or Gravity.START
            // `F-170`. The 8 dp margin, not 0. Every later rest position is
            // `margin` or `screenWidth - width - margin`, so starting flush
            // against the glass meant the very first drag ended with the
            // bubble sitting 8 dp further in than where it had begun, for no
            // reason the user could see.
            x = dp(8f)
            // Roughly a third down the screen: clear of the status bar, clear
            // of the thumb's resting place, and out of the way of the bottom
            // sheets most apps put their primary action in.
            y = resources.displayMetrics.heightPixels / 3
        }

        runCatching { windows.addView(view, lp) }
            .onSuccess {
                bubble = view
                params = lp
                // Ordered after the assignment: `windowX`/`windowY` read
                // `params`, so a spring built before it is set would take its
                // start position from a null and begin at zero.
                buildPhysics(view)
            }
    }

    private fun removeBubble() {
        cancelMotion()
        // Reset, or a service that is stopped and started again builds a fresh
        // view while `show` still believes the old one was on screen — and the
        // guard there would then skip the pop-in for the one appearance that
        // most needs it.
        wasVisible = false
        slideX = null
        settleY = null
        popX = null
        popY = null
        bubble?.let { v -> runCatching { windows.removeView(v) } }
        bubble = null
        label = null
        params = null
    }

    /**
     * Any reason to be hidden wins, and every reason is **read here** rather
     * than remembered from an event that may never have arrived.
     *
     * That is the whole fix for the bubble that would not appear: this method
     * is called on every start, every system broadcast and every nudge, and
     * each time it asks what is true now.
     */
    private fun applyVisibility() {
        val now = System.currentTimeMillis()
        val quiet = now < quietUntil
        // `F-167`. Read from storage rather than a field, so a snooze survives
        // the process being reclaimed and the phone restarting — which are the
        // two things most likely to happen during one.
        val asleep = snoozedUntil(this)
        val hidden = screenOff || quiet || appInForeground || asleep > 0L
        show(!hidden)

        // Re-check when whichever timer expires first; nothing else will wake
        // us. A snooze can be hours away, and `postDelayed` holds no wakelock,
        // so this fires late rather than never — acceptable for a button whose
        // whole job at that moment is to be absent.
        main.removeCallbacks(unquiet)
        val next = listOfNotNull(
            if (quiet) quietUntil else null,
            if (asleep > 0L) asleep else null,
        ).minOrNull()
        if (next != null) main.postDelayed(unquiet, next - now + 250L)
    }

    /**
     * `F-170`. Appear by **popping in**, disappear instantly.
     *
     * > *"as seamless as the messenger bubble icon that comes and pops up"*
     *
     * The bubble spends most of its life hidden — behind a payment, behind
     * SWIP itself, behind a snoozed afternoon — so the moment it comes back is
     * the moment the user actually sees, and it used to be a hard cut from
     * nothing to a full-size circle. That cut is why it read as an overlay
     * pasted on the screen rather than something arriving on it.
     *
     * Springing up from 60% with `DAMPING_RATIO_MEDIUM_BOUNCY` is the chat
     * head's entrance, and it costs nothing: the same two scale springs the
     * press uses, aimed somewhere else.
     *
     * **Going away is not animated, deliberately.** Three of the four reasons
     * to hide are the screen turning off, a payment app coming forward and
     * SWIP itself coming forward — all of which mean something else is already
     * taking the screen, and animating out under it would draw the eye to a
     * bubble that is supposed to be getting out of the way. The fourth, the
     * long-press snooze, does its own goodbye through [peek] before this runs.
     *
     * [wasVisible] rather than reading `view.visibility`: this method is
     * called on every broadcast and every nudge, many of which change nothing,
     * and re-popping a bubble that was already on screen would make it twitch
     * every time the user unlocked their phone.
     */
    private fun show(visible: Boolean) {
        val view = bubble ?: return

        // Checked before the no-op guard below, and `wasVisible` deliberately
        // left alone: this call has not been honoured, so the next one still
        // has to find a state that says "on screen, wants to be off".
        if (!visible) {
            val left = goodbyeUntil - System.currentTimeMillis()
            if (left > 0L) {
                main.removeCallbacks(unquiet)
                main.postDelayed(unquiet, left + 50L)
                return
            }
        }

        if (visible == wasVisible && view.visibility != View.GONE) return
        wasVisible = visible

        if (!visible) {
            cancelMotion()
            view.visibility = View.GONE
            return
        }

        view.visibility = View.VISIBLE
        // Set directly, not sprung: this is the *start* of the pop, and a
        // spring cannot be told where to begin — only where to end. Cancelling
        // first because writing a property a running animation owns is
        // undefined, and the press spring may still be settling from the tap
        // that hid it.
        runCatching { popX?.cancel(); popY?.cancel() }
        view.scaleX = 0.6f
        view.scaleY = 0.6f
        scaleTo(1f)
    }

    // ── the bubble itself ───────────────────────────────────────────────────

    /**
     * `F-158`. The shape is taken from the assistant overlay in the owner's
     * PDF (pages 22-24): a small circle parked against the screen edge that
     * **expands into a pill** when it has something to say, then settles back.
     *
     * ## Why a horizontal `LinearLayout` and not a `FrameLayout`
     *
     * Because the circle and the pill have to be **the same view at two
     * widths**, and that only works if the width is measured rather than set.
     * The window is `WRAP_CONTENT`; a 38 dp disc between two 9 dp pads
     * measures to exactly the 56 dp minimum, so it is a circle. Show the
     * label and the same measure pass makes it a pill. Nothing computes a
     * width, nothing animates one, and there is no state that can disagree
     * with what is on screen.
     *
     * A `FrameLayout` stacks its children, so the label would have been drawn
     * **on top of** the glyph inside an unchanged circle. That was the first
     * version of this method and it would have shipped as a smudge.
     *
     * ## The size, and the one number that has to move with it
     *
     * `F-170` — *"can you make sure that you increase the size a bit"*. 48 dp
     * to **56 dp**, which is Material's FAB diameter: the size Android itself
     * uses for a round thing that floats over content and is pressed with a
     * thumb. Messenger's chat head is about the same. 48 dp is the *minimum*
     * touch target — correct as a floor, too small for the one control that
     * has to be findable over somebody else's app.
     *
     * **The corner radius in `swip_bubble_bg.xml` is half of [size] and has to
     * be changed with it.** That is what makes the square case a true circle;
     * left at 24 dp on a 56 dp bubble it would be a rounded square, and
     * nothing would fail — it would just quietly stop being round.
     *
     * Built in code rather than inflated from a layout because it is one row
     * with two children, and a layout file for that is a second place to keep
     * in sync for no benefit.
     */
    @SuppressLint("ClickableViewAccessibility")
    private fun buildBubble(): View {
        val size = dp(56f)
        val disc = dp(38f)
        val pad = (size - disc) / 2

        val glyph = ImageView(this).apply {
            // Page 23: the mark is not painted onto the pill, it sits in its
            // own contrasting disc at the leading end. That is what keeps it
            // readable while the pill is widening, and what stops the
            // collapsed circle reading as a glyph lost in empty space.
            setBackgroundResource(R.drawable.swip_bubble_disc)
            setImageResource(R.drawable.swip_bubble_mark)
            // Inset within the disc. `ImageView` fits the drawable into the
            // padded content box, so this is what sizes the slash rather than
            // a second dimension to keep in sync.
            setPadding(dp(7f), dp(7f), dp(7f), dp(7f))
            layoutParams = LinearLayout.LayoutParams(disc, disc)
        }

        val text = TextView(this).apply {
            text = getString(R.string.swip_bubble_peek)
            // The one colour that is safe over SWIP's ink ground, hard-coded
            // for the same reason the drawable's are - see swip_bubble_bg.xml.
            setTextColor(0xFFF2EFE9.toInt())
            textSize = 13f
            maxLines = 1
            // GONE rather than INVISIBLE: INVISIBLE still occupies width, so
            // the bubble would be pill-shaped and empty at rest.
            visibility = View.GONE
            layoutParams = LinearLayout.LayoutParams(
                LinearLayout.LayoutParams.WRAP_CONTENT,
                LinearLayout.LayoutParams.WRAP_CONTENT,
            ).apply {
                marginStart = dp(9f)
                marginEnd = dp(3f)
            }
        }
        label = text

        return LinearLayout(this).apply {
            orientation = LinearLayout.HORIZONTAL
            gravity = Gravity.CENTER_VERTICAL
            // See the size note above: 56 dp, Material's FAB diameter, not
            // the 48 dp minimum touch target. This is pressed one-handed, at
            // a counter, usually in a hurry, over an app SWIP did not draw.
            minimumWidth = size
            minimumHeight = size
            setPadding(pad, pad, pad, pad)
            setBackgroundResource(R.drawable.swip_bubble_bg)
            // 84% rather than opaque: present without being a hole punched in
            // whatever the user is reading. `docs/32` §4 - "always there,
            // never in the way".
            alpha = 0.84f
            addView(glyph)
            addView(text)
            // `isClickable` + the `performClick` call in the listener are what
            // make this reachable by TalkBack. A bare `setOnTouchListener` on
            // a non-clickable view is invisible to every accessibility
            // service, which for a floating button is the whole feature gone.
            isClickable = true
            setOnTouchListener(DragAndTap())
            contentDescription = getString(R.string.swip_bubble_description)
            // Hidden until `applyVisibility` has had its say. Added visible,
            // there is a frame where a bubble that should be suppressed — mid
            // payment, screen off, snoozed — is drawn at full size before
            // being taken away again.
            visibility = View.GONE
        }
    }

    /**
     * Drag, edge-snap, and tap — in one listener, because Android delivers
     * them through the same stream of events and separating them means
     * guessing which one a gesture was going to be before it is finished.
     */
    private inner class DragAndTap : View.OnTouchListener {
        private var downX = 0f
        private var downY = 0f
        private var startX = 0
        private var startY = 0
        private var downAt = 0L
        private var dragging = false

        /**
         * `F-167`. Fires if the finger stays still long enough.
         *
         * Posted on DOWN and cancelled by a drag or a lift, which is how a
         * long-press has to be detected when the same listener also owns
         * dragging: you cannot know a press was long until the moment it
         * becomes one, and by then the gesture may already have been a drag.
         */
        private val longPress = Runnable {
            // `running` as well as `dragging`: the service can be destroyed
            // inside the press timeout, and a snooze nobody asked for is a
            // button that vanishes for a day on its own.
            if (dragging || !running) return@Runnable

            // `F-170`. Claimed BEFORE the snooze is written, because writing
            // it nudges the receiver, and the receiver hides the bubble. Set
            // afterwards this would be a grace period awarded to a bubble
            // that had already gone.
            goodbyeUntil = System.currentTimeMillis() + GOODBYE_MS

            snoozeForTheDay(this@SwipBubbleService)
            // Say so, in the bubble itself, in the moment before it goes. A
            // button that silently disappears when held reads as a bug.
            peek(getString(R.string.swip_bubble_snoozed))
            // A goodbye the finger can feel as well as read: the same scale
            // spring the press uses, kicked inwards so the bubble shrinks
            // under the thumb that is still on it.
            kickScale(-1.4f)
            applyVisibility()
        }

        private val slop by lazy {
            android.view.ViewConfiguration.get(this@SwipBubbleService)
                .scaledTouchSlop
        }

        /**
         * `F-170`. How fast the finger was moving when it let go.
         *
         * This is the single value that turns the snap from an animation into
         * a throw, and there is no other way to get it — `MotionEvent` carries
         * a position, never a speed. `VelocityTracker` is Android's own
         * least-squares fit over the recent history of the gesture, which is
         * why it is fed every event rather than just the last two: a
         * two-sample difference is dominated by whatever jitter the digitiser
         * produced in the final 8 ms.
         *
         * Nullable and recycled on every lift because the tracker comes from a
         * system pool. Holding one past the gesture leaks a pooled object;
         * failing to recycle it means the next gesture gets a fresh allocation
         * instead of the pooled one.
         */
        private var speed: VelocityTracker? = null

        /**
         * Above this, the *direction of the throw* picks the edge; below it,
         * the nearer edge wins.
         *
         * This is the difference between a bubble and a slider. Flick left
         * from the right-hand half of the screen and a midpoint rule sends it
         * back to the right — the gesture is ignored and it feels like the
         * bubble is fighting you. Messenger does not do that, and neither does
         * any of the chat-head implementations that were looked at.
         *
         * `scaledMinimumFlingVelocity` rather than a number of my own, because
         * it is the same threshold every list in Android uses to decide a
         * flick happened, and it is adjusted per device density.
         */
        private val flingFloor by lazy {
            android.view.ViewConfiguration.get(this@SwipBubbleService)
                .scaledMinimumFlingVelocity.toFloat()
        }

        override fun onTouch(view: View, event: MotionEvent): Boolean {
            val lp = params ?: return false

            when (event.actionMasked) {
                MotionEvent.ACTION_DOWN -> {
                    // `F-170`. The finger outranks the physics. Without this
                    // a bubble grabbed while it is still flying keeps being
                    // pulled towards the edge it was thrown at, and drags with
                    // a ghost tugging at it — the exact opposite of the direct
                    // manipulation this change is for.
                    cancelMotion()

                    downX = event.rawX
                    downY = event.rawY
                    startX = lp.x
                    startY = lp.y
                    downAt = System.currentTimeMillis()
                    dragging = false

                    speed?.recycle()
                    speed = VelocityTracker.obtain().apply { addMovement(event) }

                    main.postDelayed(
                        longPress,
                        android.view.ViewConfiguration.getLongPressTimeout()
                            .toLong(),
                    )
                    // Sprung rather than `animate().setDuration(120)`, for the
                    // reason in the physics section: a tap shorter than 120 ms
                    // used to release before the press had finished shrinking,
                    // so the two fixed animations fought and the bubble
                    // visibly hitched under a quick tap. A spring handed a new
                    // target keeps its velocity and simply turns round.
                    scaleTo(0.88f)
                    return true
                }

                MotionEvent.ACTION_MOVE -> {
                    speed?.addMovement(event)
                    val dx = event.rawX - downX
                    val dy = event.rawY - downY
                    if (!dragging && (abs(dx) > slop || abs(dy) > slop)) {
                        dragging = true
                        // Moving means this was a drag, not a hold.
                        main.removeCallbacks(longPress)
                    }
                    if (dragging) {
                        lp.x = startX + dx.toInt()
                        lp.y = startY + dy.toInt()
                        runCatching { windows.updateViewLayout(view, lp) }
                    }
                    return true
                }

                MotionEvent.ACTION_UP, MotionEvent.ACTION_CANCEL -> {
                    main.removeCallbacks(longPress)
                    scaleTo(1f)

                    // 1000 units of time = pixels per second, which is what
                    // `SpringAnimation` and `FlingAnimation` both expect. The
                    // default is pixels per millisecond and would make every
                    // throw a thousand times too slow to see.
                    val tracker = speed
                    tracker?.addMovement(event)
                    tracker?.computeCurrentVelocity(1000)
                    val vx = tracker?.xVelocity ?: 0f
                    val vy = tracker?.yVelocity ?: 0f
                    tracker?.recycle()
                    speed = null

                    if (dragging) {
                        snapToEdge(view, lp, vx, vy)
                    } else if (event.actionMasked == MotionEvent.ACTION_UP) {
                        // A tap. `ViewConfiguration`'s long-press timeout is
                        // the right boundary: anything longer was somebody
                        // holding it, probably about to drag, and opening a
                        // scanner under their finger would be a surprise.
                        val held = System.currentTimeMillis() - downAt
                        if (held < android.view.ViewConfiguration
                                .getLongPressTimeout()) {
                            // `performClick` before the work, so an
                            // accessibility service hears the click it is
                            // waiting for. Without it the bubble is a button
                            // TalkBack cannot press.
                            view.performClick()
                            openScanner()
                        }
                    }
                    return true
                }
            }
            return false
        }

        /**
         * `F-170`. Let go, and the bubble carries on doing what the finger
         * was doing — then lands.
         *
         * The old version of this method was four lines of `ValueAnimator`
         * with `duration = 260` and an `OvershootInterpolator`, and it ignored
         * the gesture entirely: where the finger was when it lifted was the
         * only input. This one takes the velocity as well, and the two axes
         * get different treatment because they are different problems.
         *
         * ## X is a spring, because there is somewhere to land
         *
         * Horizontally the bubble has exactly two rest positions — the left
         * margin and the right one. That is a spring: a fixed target, a start
         * velocity, and no duration at all. Thrown hard it arrives fast and
         * overshoots a little into the edge; nudged, it drifts across. Same
         * code, and the difference is the throw rather than a branch.
         *
         * ## Y is a fling, because there is nowhere to land
         *
         * Vertically every position is equally valid, so there is no target to
         * spring to — what should happen is that the bubble keeps travelling
         * and slows down, which is precisely what `FlingAnimation` is. Bounded
         * by `setMinValue`/`setMaxValue` so it stops at the edges of the
         * allowed strip instead of sailing off the top, which is a bubble the
         * user has to reboot to get back.
         *
         * Friction 1.1 rather than the default 1.0: slightly stickier than a
         * scrolling list, because a bubble that keeps gliding for a second
         * after you let go feels out of control when it is sitting on top of
         * somebody else's app.
         *
         * ## Why the throw direction can beat the midpoint
         *
         * See [flingFloor]. Below it, the nearer edge wins, which is what you
         * want when someone has carefully placed the bubble. Above it, the
         * direction of the throw wins, which is what you want when someone has
         * flicked it — and a midpoint rule in that case sends the bubble back
         * where it came from, which reads as the app refusing the gesture.
         */
        private fun snapToEdge(
            view: View,
            lp: WindowManager.LayoutParams,
            vx: Float,
            vy: Float,
        ) {
            val screenWidth = resources.displayMetrics.widthPixels
            val margin = dp(8f)

            parkedRight = if (abs(vx) > flingFloor) {
                vx > 0f
            } else {
                lp.x + view.width / 2 >= screenWidth / 2
            }
            val target = if (parkedRight) {
                (screenWidth - view.width - margin).toFloat()
            } else {
                margin.toFloat()
            }

            // Keep it on screen vertically too — a bubble dragged off the top
            // is a bubble the user has to reboot to get back.
            val screenHeight = resources.displayMetrics.heightPixels
            // `coerceIn(min, max)` THROWS if max < min, and max here is a
            // computed screen measurement. On a short display - or a foldable
            // read while closed - `screenHeight - height - 72dp` can land
            // under the 8 dp margin, and the exception would be thrown inside
            // a touch handler on a window the user has no way to dismiss.
            // `coerceAtLeast` first makes the range provably non-empty.
            val lowest = (screenHeight - view.height - dp(72f))
                .coerceAtLeast(margin)

            slideX?.apply {
                cancel()
                setStartVelocity(vx)
                animateToFinalPosition(target)
            }

            if (lp.y in margin..lowest && abs(vy) > flingFloor) {
                // Started inside the strip and thrown: glide, and let friction
                // decide where it stops.
                glideY = FlingAnimation(view, windowY).apply {
                    setStartVelocity(vy)
                    // `setFriction`, not `friction =` — see `springFor`.
                    setFriction(1.1f)
                    setMinValue(margin.toFloat())
                    setMaxValue(lowest.toFloat())
                    start()
                }
            } else {
                // Either barely moving, or already outside the strip because
                // the finger dragged it there. Both want the same thing: come
                // to rest at the nearest legal position, without a bounce —
                // `DAMPING_RATIO_NO_BOUNCY`, set in `buildPhysics`.
                //
                // A fling would be wrong here: `FlingAnimation` with a start
                // position outside its own min/max ends immediately, leaving
                // the bubble stranded off screen.
                settleY?.apply {
                    cancel()
                    setStartVelocity(vy)
                    animateToFinalPosition(
                        lp.y.coerceIn(margin, lowest).toFloat()
                    )
                }
            }
        }
    }

    /**
     * `F-163`. Open the scanner **over** whatever the user is in.
     *
     * This used to launch `MainActivity` with `SwipTile.EXTRA_OPEN_SCANNER`,
     * which opened the whole of SWIP full-screen — so tapping the floating
     * button took you out of the app you were standing in, which is the one
     * thing a floating button exists to avoid.
     *
     * It now opens [SwipHoverActivity]: a transparent Activity in its own
     * task, drawing a card with `ScanPage` in it over the app underneath. Same
     * camera, same detection, same resolver, same ledger — because it is the
     * same widget, not a second implementation of one.
     *
     * The Quick Settings tile still opens `MainActivity`, and should: a tile
     * press happens from the shade with nothing behind it to hover over.
     */
    private fun openScanner() {
        // A brief expansion so the tap is acknowledged before the window
        // appears. `docs/32` §4: the delay before the scanner opens is the
        // thing to hide, and a press animation is how you hide it. It matters
        // more here than it did — the hovering window starts its own Flutter
        // engine, so there is about half a second to cover.
        peek()

        val launch = Intent(this, SwipHoverActivity::class.java).apply {
            // NEW_TASK is required to start an Activity from a Service at all.
            // CLEAR_TOP rather than REORDER_TO_FRONT so a second tap restarts
            // the scanner cleanly instead of resurfacing a card whose camera
            // has already been released.
            addFlags(
                Intent.FLAG_ACTIVITY_NEW_TASK or
                    Intent.FLAG_ACTIVITY_CLEAR_TOP
            )
            // Flutter's own extra. `main()` branches on it: without this the
            // engine would come up as the entire app inside a transparent
            // window, which looks like SWIP has been pasted over the screen.
            putExtra(
                SwipHoverActivity.EXTRA_ROUTE,
                SwipHoverActivity.ROUTE_HOVER,
            )
        }

        runCatching { startActivity(launch) }
    }

    /**
     * Expand to a pill for a moment, then settle back to a circle.
     *
     * The label is held in a field rather than fetched with `getChildAt(1)`.
     * An index is a silent dependency on the order two `addView` calls happen
     * in, thirty lines away; a field breaks at compile time instead.
     */
    private fun peek(message: String = getString(R.string.swip_bubble_peek)) {
        val view = bubble ?: return
        val text = label ?: return
        if (text.visibility == View.VISIBLE) return
        text.text = message

        // This alone is what widens the bubble - the window is WRAP_CONTENT,
        // so making the label visible re-measures it into a pill.
        text.visibility = View.VISIBLE
        reanchor()

        // `F-170`. One call, no timer, no second animation waiting on the
        // first's end callback.
        //
        // This used to be `animate().scaleX(1.06f)` for 140 ms followed by a
        // `withEndAction` scaling back — two fixed animations chained through
        // a callback, so a peek arriving while the last one was mid-chain
        // produced a visible double bump, and a service destroyed between them
        // left the bubble parked at 1.06.
        //
        // A spring already rests at 1. Handing it an outward velocity and the
        // same rest position makes it bulge and return on its own, with the
        // size of the bulge set by the kick rather than by a hard-coded
        // scale: 2.5 against `STIFFNESS_MEDIUM` peaks at about 6%, which is
        // where the old number came from. Interrupting it is free.
        kickScale(2.5f)

        main.removeCallbacks(settle)
        main.postDelayed(settle, 900)
    }

    /**
     * `F-165`. Keep the pill on screen when it changes width.
     *
     * A `WRAP_CONTENT` overlay is positioned by its left edge, so showing or
     * hiding the label moves its *right* edge. Parked against the right-hand
     * side that pushed the text off the screen — the owner saw "Scanning…"
     * cropped to a single letter.
     *
     * The new width is not known until the view has been measured, which is
     * why this runs in [View.post] rather than immediately: reading
     * `view.width` on the same frame as the visibility change returns the
     * *old* width, and compensating by that is the same bug with extra steps.
     */
    private fun reanchor() {
        val view = bubble ?: return
        view.post {
            if (bubble !== view) return@post
            val margin = dp(8f)
            val screenWidth = resources.displayMetrics.widthPixels
            val target = if (parkedRight) {
                (screenWidth - view.width - margin).toFloat()
            } else {
                margin.toFloat()
            }

            // `F-170`. Sprung, not assigned.
            //
            // Two reasons, and the second is a bug rather than a polish. The
            // pill widening by ~90 px used to move the window's left edge by
            // that much in a single frame, which is a jump the eye catches on
            // the one side of the screen where the bubble is parked. And
            // writing `lp.x` directly while [slideX] is mid-flight means the
            // spring's next frame overwrites the assignment — a peek during an
            // edge snap would silently do nothing at all.
            //
            // `animateToFinalPosition` on the same spring instance is the
            // answer to both: it re-aims the motion that is already running,
            // keeping its velocity, rather than competing with it.
            slideX?.animateToFinalPosition(target)
        }
    }

    /**
     * Named rather than a lambda so [peek] can cancel a pending one. Two taps
     * inside 900 ms would otherwise queue two settles, and the second would
     * close the pill the first tap had just reopened.
     */
    private val settle = Runnable {
        label?.visibility = View.GONE
        // Narrowing moves the right edge too, so the circle would otherwise
        // be left sitting where the pill's left edge had been.
        reanchor()
    }

    // ── the notification Android requires ───────────────────────────────────

    /**
     * A foreground service is the price of an overlay that survives the user
     * leaving SWIP, and the notification is the honest part of that price:
     * there is no way to draw over other apps *quietly*, and there should not
     * be.
     *
     * `IMPORTANCE_MIN` so it never makes a sound, never peeks, and sits at the
     * bottom of the shade.
     */
    private fun startInForeground() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val manager = getSystemService(NotificationManager::class.java)
            manager.createNotificationChannel(
                NotificationChannel(
                    CHANNEL_ID,
                    getString(R.string.swip_bubble_channel),
                    NotificationManager.IMPORTANCE_MIN,
                ).apply {
                    description = getString(R.string.swip_bubble_channel_note)
                    setShowBadge(false)
                }
            )
        }

        val open = PendingIntent.getActivity(
            this,
            0,
            Intent(this, MainActivity::class.java)
                .addFlags(Intent.FLAG_ACTIVITY_NEW_TASK),
            PendingIntent.FLAG_IMMUTABLE,
        )

        val stop = PendingIntent.getService(
            this,
            1,
            Intent(this, SwipBubbleService::class.java)
                .setAction(ACTION_STOP),
            PendingIntent.FLAG_IMMUTABLE,
        )

        // `F-167`. The discoverable half of snooze. Long-pressing the bubble
        // is faster, but nobody discovers a long-press; a labelled button in
        // the shade is how people find out the gesture exists at all.
        val snooze = PendingIntent.getService(
            this,
            2,
            Intent(this, SwipBubbleService::class.java)
                .setAction(ACTION_SNOOZE_HOUR),
            PendingIntent.FLAG_IMMUTABLE,
        )

        @Suppress("DEPRECATION")
        val builder = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            Notification.Builder(this, CHANNEL_ID)
        } else {
            // The channel overload is API 26. Below it there are no channels
            // at all, and the one-argument constructor is the only form.
            Notification.Builder(this)
        }

        val notification: Notification =
            builder
                .setSmallIcon(R.drawable.swip_bubble_mark)
                .setContentTitle(getString(R.string.swip_bubble_running))
                .setContentText(getString(R.string.swip_bubble_running_note))
                .setContentIntent(open)
                .addAction(
                    Notification.Action.Builder(
                        null as android.graphics.drawable.Icon?,
                        getString(R.string.swip_bubble_snooze_hour),
                        snooze,
                    ).build()
                )
                .addAction(
                    Notification.Action.Builder(
                        // Explicitly the `Icon?` overload. `Action.Builder`
                        // also has a deprecated `(int, ...)` form, and a bare
                        // `null` resolving to the right one is an accident
                        // waiting for a toolchain bump.
                        null as android.graphics.drawable.Icon?,
                        getString(R.string.swip_bubble_turn_off),
                        stop,
                    ).build()
                )
                .setOngoing(true)
                .build()

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
            // Android 14 demands a type. SPECIAL_USE is the correct one — the
            // bubble is not a media player, a location tracker or a sync. The
            // manifest carries the matching declaration and the justification
            // string a reviewer will read.
            startForeground(
                NOTIFICATION_ID,
                notification,
                ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE,
            )
        } else {
            startForeground(NOTIFICATION_ID, notification)
        }
    }
}
