import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:swip/data/sources/capture_resolver.dart';

/// The world QR corpus.
///
/// Ideation: *"country agnostic — no matter what QR, no matter what merchant,
/// it must give me the MCC."* This is the test that holds SWIP to that, and
/// holds it to the honest version of it: a payload with no category must come
/// back as **no category**, not as a fabricated four digits.
///
/// Vectors are generated by `tool/build_qr_corpus.mjs` with real
/// CRC-16/CCITT-FALSE checksums — see that file's header for why they are
/// constructed from the spec rather than scraped off live merchants.
///
/// Regenerate with:  node tool/build_qr_corpus.mjs
void main() {
  final file = File('test/fixtures/qr_corpus.json');
  final corpus = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  final vectors = (corpus['vectors'] as List).cast<Map<String, dynamic>>();

  group('world QR corpus', () {
    test('the corpus is present and non-trivial', () {
      expect(vectors.length, greaterThanOrEqualTo(18));
    });

    for (final v in vectors) {
      final id = v['id'] as String;
      final scheme = v['scheme'] as String;
      final payload = v['payload'] as String;
      final expectMcc = v['expectMcc'] as String?;

      test('$id — $scheme', () {
        final r = CaptureResolver.resolve(payload);

        if (expectMcc == null) {
          // An honest "no category" is the PASS condition here. Returning a
          // guess would be the failure, and it is the failure mode that makes
          // a product like this actively harmful — someone picks a card on
          // the strength of a category SWIP invented.
          expect(r.hasMcc, isFalse,
              reason: 'SWIP must report no category for $id, '
                  'but returned ${r.mcc}');
        } else {
          expect(r.mcc, expectMcc,
              reason: '$scheme should yield MCC $expectMcc');
          expect(r.hasMcc, isTrue);
        }

        // Provenance is never blank — the user is always told how SWIP
        // reached its answer.
        expect(r.sourceLabel, isNotEmpty);

        if (v['expectCountry'] != null) {
          expect(r.countryCode, v['expectCountry']);
        }
        if (v['expectCurrency'] != null) {
          expect(r.currency, v['expectCurrency']);
        }
        if (v['expectMerchant'] != null) {
          expect(r.merchantName, v['expectMerchant']);
        }
        if (v['expectAcquirer'] != null) {
          expect(r.acquirer, v['expectAcquirer']);
        }
        if (v['expectRejected'] == true) {
          expect(r.kind, CaptureKind.corrupt,
              reason: 'a payload failing its own CRC must be refused, '
                  'not surfaced with a plausible-looking category');
        }
      });
    }
  });

  group('resolver invariants', () {
    test('never throws, whatever it is handed', () {
      const nasty = [
        '',
        '   ',
        '0',
        '00',
        '000201',
        'not a qr at all',
        '00020101021152',            // truncated mid-TLV
        '52045812',                  // a bare tag with no envelope
        'upi://pay?',                // scheme with no params
        'upi://pay?pa=&pn=&mc=',     // all params empty
        'upi://pay?mc=58',           // malformed mc
        '🙂🙂🙂',
        'https://',
      ];

      for (final s in nasty) {
        expect(() => CaptureResolver.resolve(s), returnsNormally,
            reason: 'resolve() threw on: "$s"');
        final r = CaptureResolver.resolve(s);
        expect(r.sourceLabel, isNotEmpty);
      }
    });

    test('a merchant key is stable across repeated reads', () {
      const payload =
          'upi://pay?pa=bluetokai@hdfcbank&pn=Blue%20Tokai&mc=5812&cu=INR';
      final a = CaptureResolver.resolve(payload).merchantKey;
      final b = CaptureResolver.resolve(payload).merchantKey;

      expect(a, isNotNull);
      expect(a, b,
          reason: 'the merchant graph is keyed on this — an unstable key '
              'silently splits one merchant into many');
    });

    test('the same merchant read twice keys identically regardless of case',
        () {
      final a = CaptureResolver.resolve(
              'upi://pay?pa=BlueTokai@HDFCBANK&mc=5812')
          .merchantKey;
      final b = CaptureResolver.resolve(
              'upi://pay?pa=bluetokai@hdfcbank&mc=5812')
          .merchantKey;

      expect(a, b,
          reason: 'VPAs are case-insensitive; keying on case would split '
              'one café into two merchants');
    });

    test('overlapping PSP hosts resolve to the most specific match', () {
      // Regression: `pages.razorpay.com` also matches the shorter
      // `razorpay.com` entry, and the two disagree about which path segment
      // carries the merchant slug. Matching the shorter one produced a
      // merchant key that never matched the same merchant twice, quietly
      // splitting one merchant into many in the graph.
      final pages =
          CaptureResolver.resolve('https://pages.razorpay.com/acmecafe');
      expect(pages.acquirer, 'Razorpay');
      expect(pages.merchantKey, 'link:razorpay:acmecafe');

      final short = CaptureResolver.resolve('https://rzp.io/l/acmecafe');
      expect(short.merchantKey, 'link:razorpay:acmecafe');

      final cashfree =
          CaptureResolver.resolve('https://payments.cashfree.com/acmecafe');
      expect(cashfree.merchantKey, 'link:cashfree:acmecafe');
    });

    test('payment links never claim a verified category', () {
      for (final url in [
        'https://rzp.io/l/rentpay',
        'https://buy.stripe.com/test_abc123',
        'https://paypal.me/someone/20',
        'https://p.paytm.me/xyz',
      ]) {
        final r = CaptureResolver.resolve(url);
        expect(r.kind, CaptureKind.paymentLink, reason: url);
        expect(r.hasMcc, isFalse,
            reason: 'an MCC is assigned by the acquirer and is not present '
                'in a URL — inferring one from $url would be a fabrication');
        expect(r.merchantKey, isNotNull,
            reason: 'the link must still key the merchant graph, which is '
                'how this vector becomes useful on the second encounter');
      }
    });
  });
}
